### ISSUE TITLE
ValueError in pialert.py

### ISSUE THREAD

**Issue by ncmoud** [pucherot/Pi.Alert#1]
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 1304, in <module>
    sys.exit(main())
  File "/home/pi/pialert/back/pialert.py", line 72, in main
    res = scan_network()
  File "/home/pi/pialert/back/pialert.py", line 355, in scan_network
    read_DHCP_leases ()
  File "/home/pi/pialert/back/pialert.py", line 492, in read_DHCP_leases
    for col1, col2, col3, col4, col5 in reader]
ValueError: need more than 2 values to unpack

**Comment by pucherot** [comment]
Hi, please, can't you send me your DHCP.leases file at '/etc/pihole/dhcp.leases'?

If you don't use Pi.hole DHCP server, please deactivate this paramenter at pialert.conf:
DHCP_ACTIVE     = False

**Comment by ncmoud** [comment]
With or without MAC addresses?

**Comment by pucherot** [comment]
You can replace the last 6 digits of all MACs with 01:02:03.

**Comment by macoud12** [comment]
```
1610449019 f8:ad:cb:01:02:03 192.168.2.199 * 01:f8:ad:cb:01:02:03
1610433714 b8:27:eb:01:02:03 192.168.2.117 pi 01:b8:27:eb:01:02:03
1610409207 00:02:9b:01:02:03 192.168.2.139 * *
1610416599 30:fd:38:01:02:03 192.168.2.11 * *
1610443699 d8:f1:5b:01:02:03 192.168.2.10 ESP_81197C *
1610411025 3a:af:1c:01:02:03 192.168.2.42 iphone 01:3a:af:1c:01:02:03
1610414175 44:07:0b:01:02:03 192.168.2.15 * *
1610409212 00:04:4b:01:02:03 192.168.2.17 * 01:00:04:4b:01:02:03
1610421579 20:df:b9:01:02:03 192.168.2.16 Google-Home-Mini *
1610415250 d4:f5:47:01:02:03 192.168.2.12 Google-Nest-Mini *
1610447063 ba:3a:9f:01:02:03 192.168.2.41 * 01:ba:3a:9f:01:02:03
1610445889 f0:18:98:01:02:03 192.168.2.25 macbook 01:f0:18:98:01:02:03
1610412319 f0:1d:bc:01:02:03 192.168.2.127 XBOX-ONE 01:f0:1d:bc:01:02:03
1610421193 30:fd:38:01:02:03 192.168.2.13 Google-Nest-Hub *
1610446073 a4:38:cc:01:02:03 192.168.2.31 * *
1610410489 a0:28:ed:01:02:03 192.168.2.40 * 01:a0:28:ed:01:02:03
1610442134 d4:f0:57:01:02:03 192.168.2.33 * *
1610431298 54:e1:ad:01:02:03 192.168.2.21 * 01:54:e1:ad:01:02:03
1610431298 f8:28:19:01:02:03 192.168.2.22 LEGION 01:f8:28:19:01:02:03
1610389698 ac:72:89:01:02:03 192.168.2.24 PAVILION 01:ac:72:89:01:02:03
1610422388 2c:33:7a:01:02:03 192.168.2.203 * 01:2c:33:7a:01:02:03
duid 00:01:00:01:27:54:df:a2:b8:27:eb:01:02:03
```

**Comment by pucherot** [comment]
ok, the problem is the last line (2 col instead of 5)
I have fixed it in v2.51
If you want, you only need to update the file "back/pialert.py"

Thank you very much for you feedback.

**Comment by ncmoud** [comment]
You're welcome. Feel free to close this issue now.

**Comment by pucherot** [comment]
fixed
