### ISSUE TITLE
Changing Port

### ISSUE THREAD

**Issue by Smugmug24** [pucherot/Pi.Alert#10]
First: Amazing Work, I love the Project! 

I have Unifi Ctrl and Pihole installed. I cant reach the http://pi.alert url. I guess it is a port Problem with Unifi. Where can i change the Port exactly? I tried on /etc/lighttpd/lighttpd.conf and /etc/lighttpd/external.conf but both wont work. 

Sorry if its a dumb question, im slowly getting into lighttpd...

Thanks

**Comment by pucherot** [comment]
Thanks.

To access the frontal via http://pi.alert/ you need two things:
- Register the name pi.alert on your DNS server at pi.hole:
   - Pi-hole -> Local DNS -> DNS Records -> Add new domain /IP
      - pi.alert 192.168.1.x (replace the 192.168.1.x with your Raspberry IP)
- Configure the web server lighttpd to redirect the request (as you has explain in your comment)

Please check if "ping pi.alert" resolve to the raspberry.
Check if http://192.168.1.x/pialert is OK (replace the 192.168.1.x with your Raspberry IP)

**Comment by Smugmug24** [comment]
Ooohh of course, forgot about that Part, my bad. Thank You!
