### ISSUE TITLE
Stuck device that pialert is running on

### ISSUE THREAD

**Issue by eugef66** [pucherot/Pi.Alert#106]
Hello, 
First, thank you for a great job with a very useful tool. 
Second, I think there is a bug in the latest release 3.0. 
After recent update, I see a stuck device in my device list. When clicked it opens a device page that pialert is running on (same MAC address), which is a separate record in DB. 
The (unknown) device is always "new" and can't be updated or deleted.

![image](https://user-images.githubusercontent.com/11634504/115631420-c6150e80-a2d3-11eb-81ee-c46341572294.png)

UPDATE: Database has two records with the same MAC and Same IP. 

![image](https://user-images.githubusercontent.com/11634504/115631688-4b002800-a2d4-11eb-9d5a-f3c04f731e59.png)

UPDATE 2: 

This is very strange behavior.  When I query database Devices table by MAC address I only get one record:

![image](https://user-images.githubusercontent.com/11634504/115769241-548f9b80-a379-11eb-98f2-8c7da277840c.png)

However I see two records with the same MAC in database in Devices tables when I query by MAC or "Is New" flag (because the stuck device is the only one marked as new in my setup) 

![image](https://user-images.githubusercontent.com/11634504/115769584-b3551500-a379-11eb-8c53-49166d0adcf4.png)

Weird

I deleted (unknown) device directly from Devices table in db, however it comes back in 5 min (after cron job run)
 

Please, advise.

**Comment by pucherot** [comment]
Solved in v3.01

**Comment by eugef66** [comment]
> 
> 
> Solved in v3.01

That was quick. Thank you. Just curios, what was the problem?

**Comment by pucherot** [comment]
Exactly!!!
