### ISSUE TITLE
Installation error on Diet Pi -  missing LWP::UserAgent module?

### ISSUE THREAD

**Issue by numbermonkey** [pucherot/Pi.Alert#110]
- Uncompressing tar file
.........................................................
- Deleting downloaded tar file...
- Settting Pi.Alert config file
- Testing Pi.Alert HW vendors database update process...
*** PLEASE WAIT A COUPLE OF MINUTES...
Can't locate LWP/UserAgent.pm in @INC (you may need to install the LWP::UserAgent module) (@INC contains: /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/arm-linux-gnueabihf/perl5/5.28 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/arm-linux-gnueabihf/perl-base) at /usr/sbin/get-iab line 36.
BEGIN failed--compilation aborted at /usr/sbin/get-iab line 36.
Can't locate LWP/UserAgent.pm in @INC (you may need to install the LWP::UserAgent module) (@INC contains: /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/arm-linux-gnueabihf/perl5/5.28 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/arm-linux-gnueabihf/perl-base) at /usr/sbin/get-oui line 31.
BEGIN failed--compilation aborted at /usr/sbin/get-oui line 31.

Pi.Alert 3.01 (2021-04-22)
---------------------------------------------------------
Update HW Vendors
    Timestamp: 2021-04-23 20:08:00

Updating vendors DB (iab & oui)...
Traceback (most recent call last):
  File "/home/dietpi/pialert/back/pialert.py", line 1486, in <module>
    sys.exit(main())
  File "/home/dietpi/pialert/back/pialert.py", line 83, in main
    res = update_devices_MAC_vendors('-s')
  File "/home/dietpi/pialert/back/pialert.py", line 264, in update_devices_MAC_vendors
    update_output = subprocess.check_output (update_args)
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['sh', '/home/dietpi/pialert/back/update_vendors.sh', '-s']' returned non-zero exit status 2.

- Testing Pi.Alert Internet IP Lookup...

**Comment by pucherot** [comment]
Please, execute this command and paste the result:
~~~
/home/dietpi/pialert/back/update_vendors.sh
~~~

**Comment by numbermonkey** [comment]
[dietpi@DietPi ~]$ /home/dietpi/pialert/back/update_vendors.sh
Updating... /usr/share/ieee-data/
########################################################################################################################## 100.0%
########################################################################################################################## 100.0%
########################################################################################################################## 100.0%
########################################################################################################################## 100.0%
########################################################################################################################## 100.0%
########################################################################################################################## 100.0%
########################################################################################################################## 100.0%
########################################################################################################################## 100.0%

Updating... /usr/share/arp-scan/
Can't locate LWP/UserAgent.pm in @INC (you may need to install the LWP::UserAgent module) (@INC contains: /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/arm-linux-gnueabihf/perl5/5.28 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/arm-linux-gnueabihf/perl-base) at /usr/sbin/get-iab line 36.
BEGIN failed--compilation aborted at /usr/sbin/get-iab line 36.
Can't locate LWP/UserAgent.pm in @INC (you may need to install the LWP::UserAgent module) (@INC contains: /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/arm-linux-gnueabihf/perl5/5.28 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/arm-linux-gnueabihf/perl-base) at /usr/sbin/get-oui line 31.
BEGIN failed--compilation aborted at /usr/sbin/get-oui line 31.
[dietpi@DietPi ~]$

**Comment by pucherot** [comment]
Please, try: 
~~~~
sudo apt-get install libwww-perl
~~~~

**Comment by numbermonkey** [comment]
that was it. lib install succeeded. ran uninstall script, rebooted, ran install script. return code 0 - all running. thank you.
