### ISSUE TITLE
python3 ~/pialert/back/pialert.py internet_IP fails

### ISSUE THREAD

**Issue by nightcustard** [pucherot/Pi.Alert#111]
Installing on a Pi 2 running Stretch 9.13 and an existing nginx installation (which may be the issue). No PiHole is installed (it's on another Pi and unbound - is this an issue?).  pialert.conf is left 'as is'.
One installation stage failed: sudo ln -s ~/pialert/install/index.html /var/www/html/index.html  ln: failed to create symbolic link '/var/www/html/index.html': File exists.  So changed the target to 'index2.html'
Everything then OK (I think) until running: python3 ~/pialert/back/pialert.py internet_IP, which failed as follows:
Pi.Alert 3.01 (2021-04-22)
---------------------------------------------------------
Check Internet IP
    Timestamp: 2021-04-23 21:26:00

Retrieving Internet IP...
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 1486, in <module>
    sys.exit(main())
  File "/home/pi/pialert/back/pialert.py", line 79, in main
    res = check_internet_IP()
  File "/home/pi/pialert/back/pialert.py", line 115, in check_internet_IP
    internet_IP = get_internet_IP()
  File "/home/pi/pialert/back/pialert.py", line 171, in get_internet_IP
    cmd_output = subprocess.check_output (dig_args, universal_newlines=True)
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['dig', '+short', '-4', 'myip.opendns.com', '@resolver1.opendns.com']' returned non-zero exit status 9

**Comment by pucherot** [comment]
Please, execute this command and paste the output:
~~~~
dig +short -4 myip.opendns.com @resolver1.opendns.com
~~~~

**Comment by nightcustard** [comment]
;; connection timed out; no servers could be reached

**Comment by pucherot** [comment]
Your router don't resolve network names.
please, can you execute:
~~~~
ip route
nslookup www.google.es
~~~~

**Comment by nightcustard** [comment]
$ ip route
default via 192.168.27.1 dev eth0 src 192.168.27.125 metric 202
192.168.27.0/24 dev eth0 proto kernel scope link src 192.168.27.125 metric
202

$ nslookup www.google.es
Server:         192.168.27.110
Address:        192.168.27.110#53

Non-authoritative answer:
Name:   www.google.es
Address: 216.58.213.3

**Comment by pucherot** [comment]
Probably your firewall or your router are blocking connections to `resolver1.opendns.com`.
Some ISP routers blocks connections to other DNS.

**Comment by nightcustard** [comment]
OK - many thanks for your very quick responses!  I'll troubleshoot
the blocking and let you know the outcome.

All the best and many thanks for the software (which I hope I can run!)

Mike

**Comment by nightcustard** [comment]
I can do a 'dig +short -4 myip.opendns.com @resolver1.opendns.com' on my
PiHole Pi with the correct result (my external IP address).
I can also ping resolver1.opendns.com OK on all Pis in my network but I get
the 'connection timed out' message when I do a 'dig +short -4
myip.opendns.com @resolver1.opendns.com'  on all the Pis other than the one
running PiHole.
The chicken's way out is to install your software on my PiHole but I'd
rather install it on a machine that's not so critical to the functioning of
my network, so I'll continue investigating...
Cheers, Mike

**Comment by nightcustard** [comment]
On my PiHole:
 $ dig resolver1.opendns.com

; <<>> DiG 9.10.3-P4-Raspbian <<>> resolver1.opendns.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21620
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
;; QUESTION SECTION:
;resolver1.opendns.com.         IN      A

;; ANSWER SECTION:
resolver1.opendns.com.  1373    IN      A       208.67.222.222

;; Query time: 15 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat Apr 24 17:33:08 BST 2021
;; MSG SIZE  rcvd: 66

On my other Pi:
 $ dig resolver1.opendns.com

; <<>> DiG 9.10.3-P4-Raspbian <<>> resolver1.opendns.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47510
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;resolver1.opendns.com.         IN      A

;; ANSWER SECTION:
resolver1.opendns.com.  1197    IN      A       208.67.222.222

;; Query time: 13 msec
;; SERVER: 192.168.27.110#53(192.168.27.110)
;; WHEN: Sat Apr 24 17:36:04 BST 2021
;; MSG SIZE  rcvd: 66

192.168.27.110 is the IP address of my PiHole.  The issue seems to be associated with the 'myip.opendns.com' part of the dig query, and I'm now out of ideas (and knowledge!).

**Comment by pucherot** [comment]
Please, execute:
`dig myip.opendns.com @resolver1.opendns.com`
and
` dig resolver1.opendns.com`
In both additional RPI (not in you pi.hole RPI).

**Comment by nightcustard** [comment]
1. mySQLserver Pi: (the one I'm trying to install PiAlert on)
***@***.***SQLserver:~ $ dig myip.opendns.com @resolver1.opendns.com

; <<>> DiG 9.10.3-P4-Raspbian <<>> myip.opendns.com @resolver1.opendns.com
;; global options: +cmd
;; connection timed out; no servers could be reached
***@***.***SQLserver:~ $ dig resolver1.opendns.com

; <<>> DiG 9.10.3-P4-Raspbian <<>> resolver1.opendns.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12628
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;resolver1.opendns.com.         IN      A

;; ANSWER SECTION:
resolver1.opendns.com.  3574    IN      A       208.67.222.222

;; Query time: 12 msec
;; SERVER: 192.168.27.110#53(192.168.27.110)
;; WHEN: Sat Apr 24 19:52:23 BST 2021
;; MSG SIZE  rcvd: 66

2. RFremotePi: (another Pi in my LAN)
pi@RFremotePi:~ $ dig myip.opendns.com @resolver1.opendns.com

; <<>> DiG 9.11.5-P4-5.1+deb10u3-Raspbian <<>> myip.opendns.com @
resolver1.opendns.com
;; global options: +cmd
;; connection timed out; no servers could be reached
pi@RFremotePi:~ $ dig resolver1.opendns.com

; <<>> DiG 9.11.5-P4-5.1+deb10u3-Raspbian <<>> resolver1.opendns.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33377
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;resolver1.opendns.com.         IN      A

;; ANSWER SECTION:
resolver1.opendns.com.  3516    IN      A       208.67.222.222

;; Query time: 12 msec
;; SERVER: 192.168.27.110#53(192.168.27.110)
;; WHEN: Sat Apr 24 19:53:21 BST 2021
;; MSG SIZE  rcvd: 66

Could it be a problem caused by the PiHole being run unbound?  I know
diddly squat really about networks, so if it's a daft question, please
ignore!

Cheers.

**Comment by pucherot** [comment]
I think the problem is that you RPI can't access to resolver1.opendns.com UDP port 53 to query DNS

Probably this command `dig www.google.com @resolver1.opendns.com` returns timeout, but this one `dig www.google.com` will be OK.

I think you have a firewall or iptables blocking DNS queries (UDP port 53) from a source IP different of your Pi.Hole system or blocking access to UDP port 53 to a different IP of your preferential DNS (8.8.8.8 1.1.1.1 ...)

**Comment by nightcustard** [comment]
Excellent!  That did it - I had a rule in my firewall to drop port 53
queries to any address other than the PiHole (to stop Google Home from
bypassing the PiHole). Disabling the rule allows the dig myip.opendns.com @
resolver1.opendns.com command to work. Obvious now you've pointed it out 😉

Very happy and thanks for your help!

Cheers, Mike
