### ISSUE TITLE
Backing up .db

### ISSUE THREAD

**Issue by p1r473** [pucherot/Pi.Alert#113]
Hi,
Has the JSON formatting from the database changed?
I had backed up my .db file from my last installation, but I recently upgraded my OS and find its not so easy to just paste the new .db file in its place
![image](https://user-images.githubusercontent.com/9235633/115941567-dcf26700-a473-11eb-9835-f979f0daf946.png)

If the JSON format has not changed, can you please let me know why backing up my .db file and replacing it later didn't work, and if so, what is the proper way to back up the database?

Thanks

![image](https://user-images.githubusercontent.com/9235633/115941639-35c1ff80-a474-11eb-8df7-d01082b7b741.png)

**Comment by pucherot** [comment]
HI

Backing up .db file and restoring it works fine.

Probably you have installed a new version of Pi.Alert (v.3.01) and restore a old version of DB (v2.70).
Please, leave the old version of DB in ~/pialert/db and execute the update script (see home page instructions)
This will create additional tables/columns/index in the old DB.

**Comment by p1r473** [comment]
Thank you!
