### ISSUE TITLE
UNIQUE constraint failed Procesising (sic) scan results

### ISSUE THREAD

**Issue by numbermonkey** [pucherot/Pi.Alert#114]
"DietPi"
[dietpi@DietPi ~]$ cat /etc/issue
Raspbian GNU/Linux 10 \n \l

Persists after running automated uninstall and occurs during reinstall.
(BTW "Processing" is spelt incorrectly :))

Scanning...
    arp-scan Method...
    Pi-hole Method...
    DHCP Leases Method...

Procesising scan results...
Traceback (most recent call last):
  File "/home/dietpi/pialert/back/pialert.py", line 1486, in <module>
    sys.exit(main())
  File "/home/dietpi/pialert/back/pialert.py", line 85, in main
    res = scan_network()
  File "/home/dietpi/pialert/back/pialert.py", line 379, in scan_network
    save_scanned_devices (arpscan_devices, cycle_interval)
  File "/home/dietpi/pialert/back/pialert.py", line 603, in save_scanned_devices
    "VALUES ( ?, ?, ?, Null, 'local_MAC') ", (cycle, local_mac, local_ip) )
sqlite3.IntegrityError: UNIQUE constraint failed: CurrentScan.cur_ScanCycle, CurrentScan.cur_MAC
- Adding jobs to the crontab...

**Comment by tcg96** [comment]
Got the same error on my Raspberry Pi 1 B running DietPi 7.0.2 (based on Debian 10). Restarted and ran the update script to try again, but it fails every time. The only device that appears is "Internet" with my public IP address.

![2021-04-24 07_56_54-ale@T440s_ _mnt_c_Users_Ale](https://user-images.githubusercontent.com/22633459/115949385-22934c00-a4d5-11eb-8ce4-8af43f6a32f2.png)

**Comment by pucherot** [comment]
Solved in v3.02
Please, try it!!

**Comment by numbermonkey** [comment]
Confirmed. Install now completes wit 3.02

**Comment by tcg96** [comment]
It works now, thank you.
