### ISSUE TITLE
Feature Request / Suggestion: Filter for a specific network only

### ISSUE THREAD

**Issue by theniwo** [pucherot/Pi.Alert#15]
I now have ALL IPs from all Networks in my localnet showing up. Including a lot of docker 172.16.0.0/16 networks. It would be great if we could limit the processing of ips to a specific network/subnet only, to not have a list of hundreds of IPs (even 169.254..).

**Comment by pucherot** [comment]
I'll study this feature.

**Comment by pucherot** [comment]
Well, I will study this functionality.
Thank you

**Comment by pucherot** [comment]
In versión 3.0 there are a new parameter in pialert.conf to define the subnet to scan with arp-scan.
~~~
SCAN_SUBNETS      = '--localnet'
~~~

You can set this parameter to '192.168.1.0/24'.

Regards.
