### ISSUE TITLE
python /home/pi/pialert/back/pialert.py update_vendors

### ISSUE THREAD

**Issue by danutzzzzz** [pucherot/Pi.Alert#160]
Hi,

If i manually run `python /home/pi/pialert/back/pialert.py update_vendors`, i see the following output, which doesnt look right.

`root@34bd7ec2f8e1:/home/pi# python /home/pi/pialert/back/pialert.py update_vendors

Pi.Alert 3.02 (2021-04-24)
---------------------------------------------------------
Update HW Vendors
    Timestamp: 2022-05-15 18:55:00

Updating vendors DB (iab & oui)...
sudo: curl: command not found
sudo: curl: command not found
sudo: curl: command not found
sudo: curl: command not found
sudo: curl: command not found
sudo: curl: command not found
sudo: curl: command not found
sudo: curl: command not found

Searching devices vendor.
    Devices Ignored:   1
    Vendors Not Found: 0
    Vendors updated:   0`

**Comment by danutzzzzz** [comment]
manually installing curl into the container allows the task to run, but fails as follows:

root@34bd7ec2f8e1:/home/pi# python /home/pi/pialert/back/pialert.py update_vendors

Pi.Alert 3.02 (2021-04-24)
---------------------------------------------------------
Update HW Vendors
    Timestamp: 2022-05-15 19:16:00

Updating vendors DB (iab & oui)...
-=O=-#     #      #         #                                                                                                                                                      
-#O=#    #       #                                                                                                                                                                 
-=O=-#     #      #         #                                                                                                                                                      
-=O#-   #      #        #                                                                                                                                                          
-#O=#    #       #                                                                                                                                                                 
-#O=#    #       #                                                                                                                                                                 
-=O=-#     #      #         #                                                                                                                                                      
-=O=-  #     #        #         #                                                                                                                                                  
Zero-sized response from from file://var/lib/ieee-data/iab.txt
Zero-sized response from from file://var/lib/ieee-data/oui.txt
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 1495, in <module>
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 81, in main
    res = update_devices_MAC_vendors()
  File "/home/pi/pialert/back/pialert.py", line 264, in update_devices_MAC_vendors
    update_output = subprocess.check_output (update_args)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['sh', '/home/pi/pialert/back/update_vendors.sh', '']' returned non-zero exit status 255

**Comment by towster** [comment]
So maybe my install or maybe not.. But when I run "arp-scan -l" from the command line I would get the following error:
```
WARNING: Cannot open MAC/Vendor file /usr/share/arp-scan/ieee-oui.txt: No such file or directory
WARNING: Cannot open MAC/Vendor file /usr/share/arp-scan/ieee-iab.txt: No such file or directory
```
I resolved this by copying the files ieee-oui.txt and ieee-iab.txt from /usr/share/arp-scan/2_backup/ directory to /usr/share/arp-scan/

After doing this the Vendor fields started populating in pi-alert.

**Comment by towster** [comment]
Ok - little digging and I fixed mine to work.. Gist of the issue is that the webserver providing the updated vendors at the URL's specified are returning a 302 (moved) and curl is not following it.  If you modify the "update_vendors.sh" file and change the http to https the updates work. So change them like so:

```
sudo curl $1 -# -O https://standards-oui.ieee.org/iab/iab.csv
sudo curl $1 -# -O https://standards-oui.ieee.org/iab/iab.txt

sudo curl $1 -# -O https://standards-oui.ieee.org/oui28/mam.csv
sudo curl $1 -# -O https://standards-oui.ieee.org/oui28/mam.txt

sudo curl $1 -# -O https://standards-oui.ieee.org/oui36/oui36.csv
sudo curl $1 -# -O https://standards-oui.ieee.org/oui36/oui36.txt

sudo curl $1 -# -O https://standards-oui.ieee.org/oui/oui.csv
sudo curl $1 -# -O https://standards-oui.ieee.org/oui/oui.txt

```

**Comment by danutzzzzz** [comment]
> 

thank you!
