### ISSUE TITLE
Error Updating Device - readonly database

### ISSUE THREAD

**Issue by danutzzzzz** [pucherot/Pi.Alert#161]
Whatever device i try to update the values of, i get the following error:

```
Error Updating Device

UPDATE Devices SET
dev_Name = "Router",
dev_Owner = "Home",
dev_DeviceType = "Router",
dev_Vendor = "TP-LINK TECHNOLOGIES CO.,LTD.",
dev_Favorite = "0",
dev_Group = "(unknown)",
dev_Comments = "",
dev_StaticIP = "0",
dev_ScanCycle = "1",
dev_AlertEvents = "1",
dev_AlertDeviceDown = "0",
dev_SkipRepeated = "0"
WHERE dev_MAC="a4:2b:b0:d9:19:a9"

attempt to write a readonly database
```

```
root@Nexus-App:/home/pi# ls -l pialert
total 76
-rw-r--r-- 1 root root 35149 May 15 15:23 LICENSE.txt
-rw-r--r-- 1 root root  5001 May 15 15:23 README.md
drwxr-xr-x 2 root root  4096 May 15 15:23 back
drwxr-xr-x 1 root root  4096 May 16 11:00 config
drwxr-xr-x 2 pi   pi    4096 May 16 11:10 db
drwxr-xr-x 3 root root  4096 May 15 15:23 docs
drwxr-xr-x 7 root root  4096 May 15 15:23 front
drwxr-xr-x 2 root root  4096 May 15 15:23 install
drwxr-xr-x 2 pi   pi    4096 May 16 04:00 log
drwxr-xr-x 2 root root  4096 May 15 15:23 tar
```

```
root@Nexus-App:/home/pi# ls -l pialert/db
total 324
-rwxr-xr-x 1 pi pi 331776 May 16 11:10 pialert.db
```

**Comment by WildWeasel109** [comment]
Just checked my db and noticed that my group (www-data) is different to yours:
<img width="534" alt="image" src="https://user-images.githubusercontent.com/77530271/168649611-b78c83f6-e701-4091-9abc-f5dc9f76322a.png">

Not sure if that helps, but I'm not seeing any issues.

**Comment by danutzzzzz** [comment]
> Just checked my db and noticed that my group (www-data) is different to yours: <img alt="image" width="534" src="https://user-images.githubusercontent.com/77530271/168649611-b78c83f6-e701-4091-9abc-f5dc9f76322a.png">
> 
> Not sure if that helps, but I'm not seeing any issues.

thanks but nothing seems to resolve the issue :(

**Comment by leiweibau** [comment]
You can try the commands, you could find in the "Step-by-Step" Install guide at point 5.10

`sudo chgrp -R www-data ~/pialert/db`
`chmod -R 770 ~/pialert/db`

The group of the db folder must be www-data.
