### ISSUE TITLE
you always seem to be logged in - can you log out?

### ISSUE THREAD

**Issue by Just-another-pleb** [pucherot/Pi.Alert#174]
As `Pi.Alert` is supposed to be a detector for any new devices connecting to your network:

I see it strange that the web page is always in a mode where you can edit/add/delete devices.

So - if someone nasty gets into your network - they can simply go to that page and adjust things so you don't know there is a new device connected.

Seems a bit odd.

**Comment by leiweibau** [comment]
You can use webserver features like .htaccess to protect your pialert installation. With the default lighttpd it is a bit more complicated, but you can also use nginx or apache with pialert.

**Comment by Just-another-pleb** [comment]
Thanks.
