### ISSUE TITLE
Error running scan

### ISSUE THREAD

**Issue by kotahukka** [pucherot/Pi.Alert#18]
After installing pialert I get the below error.  This is what I have for ssh session.

python ~/pialert/back/pialert.py update_vendors

Pi.Alert 2.52 (2021-01-11)
---------------------------------------------------------
Update HW Vendors
    Timestamp: 2021-01-13 10:53:00

Updating vendors DB (iab & oui)...
############################################################################################################################ 100.0%

Searching devices vendor.
    Devices Ignored:   1
    Vendors Not Found: 0
    Vendors updated:   0
 
python ~/pialert/back/pialert.py internet_IP

Pi.Alert 2.52 (2021-01-11)
---------------------------------------------------------
Check Internet IP
    Timestamp: 2021-01-13 10:54:00

Retrieving Internet IP...
    Error retrieving Internet IP
    Exiting...

(using info from https://github.com/pucherot/Pi.Alert/issues/12) I updated line 160 of pialert.py

python ~/pialert/back/pialert.py internet_IP

Pi.Alert 2.52 (2021-01-11)
---------------------------------------------------------
Check Internet IP
    Timestamp: 2021-01-13 10:59:00

Retrieving Internet IP...
    75.57.12#.#

Retrieving previous IP...
    0.0.0.0
    Saving new IP
        IP updated

Skipping Dynamic DNS update...

DONE!!!

python ~/pialert/back/pialert.py 1

Pi.Alert 2.52 (2021-01-11)
---------------------------------------------------------
Scan Devices
    ScanCycle: 1
    Timestamp: 2021-01-13 11:00:00

Scanning...
    arp-scan Method...
    Pi-hole Method...
    DHCP Leases Method...

Procesising scan results...
    Devices Detected.......: 42
        arp-scan Method....: 42
        Pi-hole Method.....: +0
        New Devices........: 42

    Devices in this cycle..: 0
        Down Alerts........: 0
        New Down Alerts....: 0
        New Connections....: 0
        Disconnections.....: 0
        IP Changes.........: 0

Updating DB Info...
    Sessions Events (connect / discconnect) ...
    Creating new devices...
    Updating Devices Info...
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 1313, in <module>
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 72, in main
    res = scan_network()
  File "/home/pi/pialert/back/pialert.py", line 379, in scan_network
    update_devices_data_from_scan ()
  File "/home/pi/pialert/back/pialert.py", line 827, in update_devices_data_from_scan
    vendor = query_MAC_vendor (device['dev_MAC'])
  File "/home/pi/pialert/back/pialert.py", line 296, in query_MAC_vendor
    mac = pMAC.replace (':','')
AttributeError: 'int' object has no attribute 'replace'

Did I miss something when installing?

**Comment by pucherot** [comment]
Solved in issue #6.
Please update "back/pialert.py" with v2.54.
BR
