### ISSUE TITLE
Vendor database still not updating

### ISSUE THREAD

**Issue by alansenairj** [pucherot/Pi.Alert#197]
- Uncompressing tar file
.........................................................
- Deleting downloaded tar file...
- Settting Pi.Alert config file
- Testing Pi.Alert HW vendors database update process...
*** PLEASE WAIT A COUPLE OF MINUTES...
Zero-sized response from from file://var/lib/ieee-data/iab.txt
Zero-sized response from from file://var/lib/ieee-data/oui.txt

Pi.Alert 3.02 (2021-04-24)
---------------------------------------------------------
Update HW Vendors
    Timestamp: 2022-08-28 17:47:00

Updating vendors DB (iab & oui)...
Traceback (most recent call last):
  File "/root/pialert/back/pialert.py", line 1488, in <module>
    sys.exit(main())       
  File "/root/pialert/back/pialert.py", line 83, in main
    res = update_devices_MAC_vendors('-s')
  File "/root/pialert/back/pialert.py", line 264, in update_devices_MAC_vendors
    update_output = subprocess.check_output (update_args)
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['sh', '/root/pialert/back/update_vendors.sh', '-s']' returned non-zero exit status 255.

- Testing Pi.Alert Internet IP Lookup...

Pi.Alert 3.02 (2021-04-24)
---------------------------------------------------------
Check Internet IP
    Timestamp: 2022-08-28 17:47:00

Retrieving Internet IP...
    177.12.5.115

Retrieving previous IP...
    0.0.0.0
    Saving new IP
        IP updated

Skipping Dynamic DNS update...

DONE!!!

- Testing Pi.Alert Network scan...
*** PLEASE WAIT A COUPLE OF MINUTES...
WARNING: Cannot open MAC/Vendor file /usr/share/arp-scan/ieee-oui.txt: No such file or directory
WARNING: Cannot open MAC/Vendor file /usr/share/arp-scan/ieee-iab.txt: No such file or directory
grep: /usr/share/arp-scan/ieee-oui.txt: No such file or directory

**Comment by alansenairj** [comment]
![image](https://user-images.githubusercontent.com/20565821/187095055-d93eb96e-c608-43ef-91b1-e73e2e73df57.png)

**Comment by alansenairj** [comment]
there is something in a arp scan output that empty files: 

![image](https://user-images.githubusercontent.com/20565821/187095180-a325796f-d069-4528-84e7-973b02d6e41b.png)

**Comment by francouai** [comment]
same problem for me on a fresh install.

**Comment by francouai** [comment]
```
pi@Pi-Hole:~ $ python ~/pialert/back/pialert.py update_vendors

Pi.Alert 3.02 (2021-04-24)
---------------------------------------------------------
Update HW Vendors
    Timestamp: 2022-09-06 07:25:00

Updating vendors DB (iab & oui)...
#=O#-   #     #
#=O#-   #     #
-#O=-#    #      #
#=O#-   #     #
-#O=-#    #      #
-#O=-#    #      #
-#O=-#    #      #
-#O=-#    #      #
Zero-sized response from from file://var/lib/ieee-data/iab.txt
Zero-sized response from from file://var/lib/ieee-data/oui.txt
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 1488, in <module>
    sys.exit(main())
  File "/home/pi/pialert/back/pialert.py", line 81, in main
    res = update_devices_MAC_vendors()
  File "/home/pi/pialert/back/pialert.py", line 264, in update_devices_MAC_vendors
    update_output = subprocess.check_output (update_args)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['sh', '/home/pi/pialert/back/update_vendors.sh', '']' returned non-zero exit status 255
```

**Comment by leiweibau** [comment]
This error has already resulted in several reports, which have also been answered several times. @pucherot has not responded to pull requests and issues for a long time. If you want to use a maintained version of Pi.Alert that has fixed this and also other bugs, have a look at the forks.

**Comment by francouai** [comment]
I just saw few devs took action to update Pi-Alert with their own knowledge.. that's great.  
I'll de-install the official version and check which one from the two modded version will be the best.

**Comment by alansenairj** [comment]
> This error has already resulted in several reports, which have also been answered several times. @pucherot has not responded to pull requests and issues for a long time. If you want to use a maintained version of Pi.Alert that has fixed this and also other bugs, have a look at the forks.

Hi Leiweibau. I am using your fork and it has this problem too. You fork is amazing and have more features. But is really hard to get vendors merge to db. 

I got a problem to use update_vendors.sh too. 

I removed comment and put to get iab and oui from ieee site and it write to output file correctly but it still not merging this to sqlplus database. 

Can you help me?

**Comment by alansenairj** [comment]
############################################################
 Pi.Alert Installation
############################################################
Fri 09 Sep 2022 12:46:39 PM -03
Logfile: pialert_install_2022-09-09_12-46.log

************************************************************
************************************************************
**            ERROR INSTALLING PI.ALERT                   **
************************************************************
************************************************************

Pi.Alert path already exists: /home/pi/pialert

Use 'cat pialert_install_2022-09-09_12-46.log' to view installation log

pi@raspberrypi:~ $ rm -rf pialert
pi@raspberrypi:~ $ ./pialert_install.sh 

############################################################
 Pi.Alert Installation
############################################################
Fri 09 Sep 2022 12:47:28 PM -03
Logfile: pialert_install_2022-09-09_12-47.log

------------------------------------------------------------
 Pi-hole
------------------------------------------------------------
- Checking if 'pi.alert' is configured in Local DNS...
- Adding 'pi.alert' to Local DNS...

------------------------------------------------------------
 Lighttpd & PHP
------------------------------------------------------------
- Installing apt-utils...
- Installing lighttpd...
- Installing PHP...
- Activating PHP...
- Restarting lighttpd...
- Installing sqlite3...

------------------------------------------------------------
 arp-scan & dnsutils
------------------------------------------------------------
####Note - it founds because I link and update files before reinstall

- Installing arp-scan...
- Testing arp-scan...
192.168.129.10	xxxxxxxxxxxxxxxxx	TP-LINK TECHNOLOGIES CO.,LTD.
192.168.129.2	xxxxxxxxxxxx	PCS Systemtechnik GmbH
192.168.129.49	xxxxxxxxxxxx	GIGA-BYTE TECHNOLOGY CO.,LTD.
192.168.129.8	xxxxxxxxxxxxxxxx	Routerboard.com
192.168.129.3	xxxxxxxxxxxxxx	Cisco Systems, Inc
192.168.129.3	0xxxxxxb7	SAMSUNG ELECTRO-MECHANICS(THAILAND)
192.168.129.8	08:0xxxxxxxx81:a6:a6	PCS Systemtechnik GmbH
192.168.129.20	xxxxxxxxxxxxxx	LG Innotek
192.168.129.2	4xxxxxxxxxxx1	NVIDIA Corporation
192.168.129.22	xxxxxxxxxxx	Hon Hai Precision Ind. Co.,Ltd.
192.168.129.14	xxxxxxxxxxxx	(Unknown)
- Installing dnsutils & net-tools...

------------------------------------------------------------
 Python
------------------------------------------------------------
- Checking Python 2...
  - Python 2 is installed
    - Python 2.7.16

- Checking Python 3...
  - Python 3 is installed
    - Python 3.7.3

- Using the available Python version installed
  - Python 3 is available

- Using Python 3

------------------------------------------------------------
 Pi.Alert
------------------------------------------------------------
- Downloading installation tar file...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 55.9M  100 55.9M    0     0  6288k      0  0:00:09  0:00:09 --:--:-- 10.5M

- Uncompressing tar file
.........................................................
- Deleting downloaded tar file...
- Settting Pi.Alert config file
- Testing Pi.Alert HW vendors database update process...
*** PLEASE WAIT A COUPLE OF MINUTES...
Zero-sized response from from file://var/lib/ieee-data/iab.txt
Zero-sized response from from file://var/lib/ieee-data/oui.txt

Pi.Alert 3.02 (2021-04-24)
---------------------------------------------------------
Update HW Vendors
    Timestamp: 2022-09-09 12:48:00

Updating vendors DB (iab & oui)...
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 1488, in <module>
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 83, in main
    res = update_devices_MAC_vendors('-s')
  File "/home/pi/pialert/back/pialert.py", line 264, in update_devices_MAC_vendors
    update_output = subprocess.check_output (update_args)
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['sh', '/home/pi/pialert/back/update_vendors.sh', '-s']' returned non-zero exit status 255.

- Testing Pi.Alert Internet IP Lookup...

Pi.Alert 3.02 (2021-04-24)
---------------------------------------------------------
Check Internet IP
    Timestamp: 2022-09-09 12:48:00

Retrieving Internet IP...
    191.135.162.57

Retrieving previous IP...
    0.0.0.0
    Saving new IP
        IP updated

Skipping Dynamic DNS update...

DONE!!!



- Testing Pi.Alert Network scan...
*** PLEASE WAIT A COUPLE OF MINUTES...
grep: /usr/share/arp-scan/ieee-oui.txt: No such file or directory
grep: /usr/share/arp-scan/ieee-oui.txt: No such file or directory
grep: /usr/share/arp-scan/ieee-oui.txt: No such file or directory
grep: /usr/share/arp-scan/ieee-oui.txt: No such file or directory

Pi.Alert 3.02 (2021-04-24)
---------------------------------------------------------
Scan Devices
    ScanCycle: 1
    Timestamp: 2022-09-09 12:48:00

Scanning...
    arp-scan Method...
    Pi-hole Method...
    DHCP Leases Method...

Processing scan results...
    Devices Detected.......: 13
        arp-scan Method....: 11
        Pi-hole Method.....: +0
        New Devices........: 12

    Devices in this cycle..: 1
        Down Alerts........: 0
        New Down Alerts....: 0
        New Connections....: 0
        Disconnections.....: 0
        IP Changes.........: 0

Updating DB Info...
    Sessions Events (connect / discconnect) ...
    Creating new devices...
    Updating Devices Info...
        Trying to resolve devices without name.....................
        Names updated:   0
    Voiding false (ghost) disconnections...
    Pairing session events (connection / disconnection) ...
    Creating sessions snapshot...
    Skipping repeated notifications...

Reporting...
    Formating report...
    Skip mail...
    Notifications: 20

DONE!!!



- Set devices as Known devices...
- Adding jobs to the crontab...
- Setting permissions...
- Publishing Pi.Alert web...
- Configuring http://pi.alert/ redirection...
- Restarting lighttpd...

------------------------------------------------------------
 Installation process finished
------------------------------------------------------------
Use: - http://pi.alert/
     - http://192.168.129.244/pialert/
To access Pi.Alert web

**Comment by alansenairj** [comment]
this installation is always emptying iab and oui files!

pi@raspberrypi:/var/lib/ieee-data $ ls -l
total 1104
lrwxrwxrwx 1 root root     28 Aug  5  2018 iab.csv -> /usr/share/ieee-data/iab.csv
lrwxrwxrwx 1 root root     28 Sep  9 12:26 iab.txt -> /usr/share/ieee-data/iab.txt
-rw-r--r-- 1 root root 140432 Sep  9 12:28 ieee-iab.txt
-rw-r--r-- 1 root root 984358 Sep  9 12:28 ieee-oui.txt
lrwxrwxrwx 1 root root     28 Aug  5  2018 mam.csv -> /usr/share/ieee-data/mam.csv
lrwxrwxrwx 1 root root     28 Aug  5  2018 mam.txt -> /usr/share/ieee-data/mam.txt
lrwxrwxrwx 1 root root     30 Aug  5  2018 oui36.csv -> /usr/share/ieee-data/oui36.csv
lrwxrwxrwx 1 root root     30 Aug  5  2018 oui36.txt -> /usr/share/ieee-data/oui36.txt
lrwxrwxrwx 1 root root     28 Aug  5  2018 oui.csv -> /usr/share/ieee-data/oui.csv
lrwxrwxrwx 1 root root     28 Sep  9 12:27 oui.txt -> /usr/share/ieee-data/oui.txt
pi@raspberrypi:/var/lib/ieee-data $ cd /usr/share/ieee-data/
pi@raspberrypi:/usr/share/ieee-data $ ls -l
total 4
drwxr-xr-x 2 root root 4096 Aug 28 17:28 2_backup
-rw-r--r-- 1 root root    0 Sep  9 12:48 iab.csv
-rw-r--r-- 1 root root    0 Sep  9 12:48 iab.txt
-rw-r--r-- 1 root root    0 Sep  9 12:48 mam.csv
-rw-r--r-- 1 root root    0 Sep  9 12:48 mam.txt
-rw-r--r-- 1 root root    0 Sep  9 12:48 oui36.csv
-rw-r--r-- 1 root root    0 Sep  9 12:48 oui36.txt
-rw-r--r-- 1 root root    0 Sep  9 12:48 oui.csv
-rw-r--r-- 1 root root    0 Sep  9 12:48 oui.txt

**Comment by alansenairj** [comment]
pi@raspberrypi:~/pialert/back $ ./update_vendors.sh 
Updating... /usr/share/ieee-data/
-#O=#   #    #                                                                                                      
##O=#    #                                                                                                          
##O=#    #                                                                                                          
-#O=#   #    #                                                                                                      
-=#=-#    #    #                                                                                                    
##O=#    #                                                                                                          
-#O=#   #    #                                                                                                      
##O=#    #                                                                                                          

Updating... /usr/share/arp-scan/
Fetching IAB data from file://var/lib/ieee-data/iab.txt
Zero-sized response from from file://var/lib/ieee-data/iab.txt
Fetching OUI data from file://var/lib/ieee-data/oui.txt
Zero-sized response from from file://var/lib/ieee-data/oui.txt

**Comment by leiweibau** [comment]
It works in my case.
Are you using pi-hole, or any other blocking device?

These are the links:
https://standards-oui.ieee.org/iab/iab.csv
https://standards-oui.ieee.org/iab/iab.txt
https://standards-oui.ieee.org/oui28/mam.csv
https://standards-oui.ieee.org/oui28/mam.txt
https://standards-oui.ieee.org/oui36/oui36.csv
https://standards-oui.ieee.org/oui36/oui36.txt
https://standards-oui.ieee.org/oui/oui.csv
https://standards-oui.ieee.org/oui/oui.txt

Check if you can open these links in your browser.

**Comment by alansenairj** [comment]
![image](https://user-images.githubusercontent.com/20565821/189391840-11df8929-913b-4cfb-a8a8-b0914a684a05.png)

**Comment by leiweibau** [comment]
This is not my updatescript.
[https://github.com/leiweibau/Pi.Alert/blob/main/back/update_vendors.sh](https://github.com/leiweibau/Pi.Alert/blob/main/back/update_vendors.sh)

**Comment by alansenairj** [comment]
pi@raspberrypi:~ $ pip3 install --upgrade requests
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting requests
  Downloading https://files.pythonhosted.org/packages/ca/91/6d9b8ccacd0412c08820f72cebaa4f0c0441b5cda699c90f618b6f8a1b42/requests-2.28.1-py3-none-any.whl (62kB)
    100% |████████████████████████████████| 71kB 1.5MB/s 
Requirement already satisfied, skipping upgrade: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests) (2.6)
Requirement already satisfied, skipping upgrade: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests) (1.26.12)
Collecting charset-normalizer<3,>=2 (from requests)
  Downloading https://files.pythonhosted.org/packages/db/51/a507c856293ab05cdc1db77ff4bc1268ddd39f29e7dc4919aa497f0adbec/charset_normalizer-2.1.1-py3-none-any.whl
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests) (2018.8.24)
Installing collected packages: charset-normalizer, requests
Successfully installed charset-normalizer-2.1.1 requests-2.28.1
pi@raspberrypi:~ $ rm -rf pialert
pi@raspberrypi:~ $ curl -sSL https://github.com/leiweibau/Pi.Alert/raw/main/install/pialert_install.sh | bash

############################################################
 Pi.Alert Installation
############################################################
Fri 09 Sep 2022 01:17:03 PM -03
Logfile: pialert_install_2022-09-09_13-17.log

------------------------------------------------------------
 Pi-hole
------------------------------------------------------------
- Checking if 'pi.alert' is configured in Local DNS...
  - 'pi.alert' already in Local DNS...

------------------------------------------------------------
 Lighttpd & PHP
------------------------------------------------------------
- Installing apt-utils...
- Installing lighttpd...
- Installing PHP...
- Activating PHP...
- Restarting lighttpd...
- Installing sqlite3...

------------------------------------------------------------
 arp-scan, dnsutils and nmap
------------------------------------------------------------
- Installing arp-scan...
- Testing arp-scan...
I modified it
192.168.129.a	xxx	TP-LINK TECHNOLOGIES CO.,LTD.
192.168.129.aa	xxx	PCS Systemtechnik GmbH
192.168.129.a	xxx	SAMSUNG ELECTRO-MECHANICS(THAILAND)
192.168.129.a	xxx	GIGA-BYTE TECHNOLOGY CO.,LTD.
192.168.129.a	xxx	Routerboard.com
192.168.129.a	xxx	(Unknown)
192.168.129.a	xxx	Cisco Systems, Inc
192.168.129.a	xxx	PCS Systemtechnik GmbH
192.168.129.a	xxx	NVIDIA Corporation
192.168.129.a	xxx	LG Innotek
192.168.129.a	xxx	Hon Hai Precision Ind. Co.,Ltd.
192.168.129.a	xxx	TP-LINK TECHNOLOGIES CO.,LTD. (DUP: 2)
- Installing dnsutils & net-tools...
- Installing nmap and zip...

------------------------------------------------------------
 Python
------------------------------------------------------------
- Checking Python 2...
  - Python 2 is installed
    - Python 2.7.16

- Checking Python 3...
  - Python 3 is installed
    - Python 3.7.3

- Using the available Python version installed
  - Python 3 is available

- Using Python 3

------------------------------------------------------------
 Pi.Alert
------------------------------------------------------------
- Downloading installation tar file...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 58.3M  100 58.3M    0     0   9.8M      0  0:00:05  0:00:05 --:--:-- 11.1M

- Uncompressing tar file
...........................................................
- Deleting downloaded tar file...
- Settting Pi.Alert config file
- Testing Pi.Alert HW vendors database update process...
*** PLEASE WAIT A COUPLE OF MINUTES...

Pi.Alert 3.6_leiweibau (2022-08-22)
---------------------------------------------------------
Update HW Vendors
    Timestamp: 2022-09-09 13:17:00

Updating vendors DB (iab & oui)...

Searching devices vendor.
    Devices Ignored:   1
    Vendors Not Found: 0
    Vendors updated:   0

- Testing Pi.Alert Internet IP Lookup...

Pi.Alert 3.6_leiweibau (2022-08-22)
---------------------------------------------------------
Check Internet IP
    Timestamp: 2022-09-09 13:19:00

Retrieving Internet IP...
    191.135.162.57

Retrieving previous IP...
    191.135.162.57
    No changes to perform

Skipping Dynamic DNS update...

DONE!!!



- Testing Pi.Alert Network scan...
*** PLEASE WAIT A COUPLE OF MINUTES...

Pi.Alert 3.6_leiweibau (2022-08-22)
---------------------------------------------------------
Scan Devices
    ScanCycle: 1
    Timestamp: 2022-09-09 13:19:00

Scanning...
    arp-scan Method...
    Pi-hole Method...
    DHCP Leases Method...

Processing scan results...
    Devices Detected.......: 14
        arp-scan Method....: 11
        Pi-hole Method.....: +0
        New Devices........: 13

    Devices in this cycle..: 1
        Down Alerts........: 0
        New Down Alerts....: 0
        New Connections....: 0
        Disconnections.....: 0
        IP Changes.........: 0

Updating DB Info...
    Sessions Events (connect / discconnect) ...
    Creating new devices...
    Updating Devices Info...
        Trying to resolve devices without name.....................
        Names updated:   0
    Voiding false (ghost) disconnections...
    Pairing session events (connection / disconnection) ...
    Creating sessions snapshot...
    Skipping repeated notifications...

Reporting...
    Formating report...
    Skip mail...
    Skip PUSHSAFER...
    Skip NTFY...
    Notifications: 20

DONE!!!



- Enable optional Speedtest...

- Enable optional pialert-cli...

- Set devices as Known devices...
- Pi.Alert crontab jobs already exists. This is your crontab:
#  pialert.cron - Back module. Crontab jobs
0 3 * * 1      python3 ~/pialert/back/pialert.py update_vendors >~/pialert/log/pialert.vendors.log  2>&1
*/3 * * * *    python3 ~/pialert/back/pialert.py internet_IP    >~/pialert/log/pialert.IP.log       2>&1
*/5 * * * *    python3 ~/pialert/back/pialert.py 1              >~/pialert/log/pialert.1.log        2>&1
0 2 * * */4      python3 ~/pialert/back/pialert.py cleanup        >~/pialert/log/pialert.cleanup.log  2>&1
#*/15 * * * *   python3 ~/pialert/back/pialert.py 15             >~/pialert/log/pialert.15.log       2>&1
- Deleting previous Pi.Alert site
- Setting permissions...
- Publishing Pi.Alert web...
- Configuring http://pi.alert/ redirection...
- Restarting lighttpd...

------------------------------------------------------------
 Installation process finished
------------------------------------------------------------
Use: - http://pi.alert/
     - http://192.168.129.244/pialert/
To access Pi.Alert web

pi@raspberrypi:~ $ cd /usr/share/ieee-data/
pi@raspberrypi:/usr/share/ieee-data $ ls -l
total 13392
drwxr-xr-x 2 root root    4096 Aug 28 17:28 2_backup
-rw-r--r-- 1 root root  381459 Sep  9 13:17 iab.csv
-rw-r--r-- 1 root root 2453481 Sep  9 13:18 iab.txt
-rw-r--r-- 1 root root  484233 Sep  9 13:18 mam.csv
-rw-r--r-- 1 root root  822563 Sep  9 13:18 mam.txt
-rw-r--r-- 1 root root  458484 Sep  9 13:18 oui36.csv
-rw-r--r-- 1 root root  815820 Sep  9 13:18 oui36.txt
-rw-r--r-- 1 root root 3023511 Sep  9 13:18 oui.csv
-rw-r--r-- 1 root root 5251729 Sep  9 13:18 oui.txt
pi@raspberrypi:/usr/share/ieee-data $ cd
pi@raspberrypi:~ $ cd pialert/back/
pi@raspberrypi:~/pialert/back $ ls
pialert-cli  pialert.py  report_template.html  report_template.txt  speedtest-cli  update_vendors.sh
pi@raspberrypi:~/pialert/back $ chmod a+x update_vendors.sh 
pi@raspberrypi:~/pialert/back $ ./update_vendors.sh 
Updating... /usr/share/ieee-data/
############################################################################################################## 100.0%
############################################################################################################## 100.0%
############################################################################################################## 100.0%
############################################################################################################## 100.0%
############################################################################################################## 100.0%
############################################################################################################## 100.0%
############################################################################################################## 100.0%
############################################################################################################## 100.0%

Updating... /usr/share/arp-scan/
Renaming ieee-iab.txt to ieee-iab.txt.bak
Fetching IAB data from file://var/lib/ieee-data/iab.txt
Fetched 2453481 bytes
Opening output file ieee-iab.txt
4575 IAB entries written to file ieee-iab.txt
Renaming ieee-oui.txt to ieee-oui.txt.bak
Fetching OUI data from file://var/lib/ieee-data/oui.txt
Fetched 5251729 bytes
Opening output file ieee-oui.txt
32576 OUI entries written to file ieee-oui.txt
pi@raspberrypi:~/pialert/back $ python3 pialert.py update_vendors

Pi.Alert 3.6_leiweibau (2022-08-22)
---------------------------------------------------------
Update HW Vendors
    Timestamp: 2022-09-09 13:22:00

Updating vendors DB (iab & oui)...
############################################################################################################## 100.0%
############################################################################################################## 100.0%
############################################################################################################## 100.0%
############################################################################################################## 100.0%
############################################################################################################## 100.0%
############################################################################################################## 100.0%
############################################################################################################## 100.0%
############################################################################################################## 100.0%

Searching devices vendor....................
    Devices Ignored:   1
    Vendors Not Found: 4
    Vendors updated:   15
pi@raspberrypi:~/pialert/back $ python3 pialert.py 1

Pi.Alert 3.6_leiweibau (2022-08-22)
---------------------------------------------------------
Scan Devices
    ScanCycle: 1
    Timestamp: 2022-09-09 13:23:00

Scanning...
    arp-scan Method...
    Pi-hole Method...
    DHCP Leases Method...

Processing scan results...
    Devices Detected.......: 14
        arp-scan Method....: 10
        Pi-hole Method.....: +0
        New Devices........: 0

    Devices in this cycle..: 14
        Down Alerts........: 0
        New Down Alerts....: 0
        New Connections....: 0
        Disconnections.....: 0
        IP Changes.........: 0

Updating DB Info...
    Sessions Events (connect / discconnect) ...
    Creating new devices...
    Updating Devices Info...
        Trying to resolve devices without name.....................
        Names updated:   0
    Voiding false (ghost) disconnections...
    Pairing session events (connection / disconnection) ...
    Creating sessions snapshot...
    Skipping repeated notifications...

Reporting...
    Formating report...
    No changes to report...
    Notifications: 0

DONE!!!

**Comment by leiweibau** [comment]
Looks good, so far.

**Comment by alansenairj** [comment]
> 
:(

![image](https://user-images.githubusercontent.com/20565821/189398199-13c89ca8-80fb-40b7-a7c6-4f892870f5ff.png)

**Comment by alansenairj** [comment]
It is trick for me to get a stage about to merge vendors in database. I don´t know how this database works

**Comment by leiweibau** [comment]
The Vendor DB is for the MAC adresses (Raspberry Pi Foundation, Samsung Electronics Co.,Ltd, etc)

**Comment by alansenairj** [comment]
> The Vendor DB is for the MAC adresses (Raspberry Pi Foundation, Samsung Electronics Co.,Ltd, etc)

Is it to show me what is vendor is instead ""unknow" in this main dashbord? 

Do I need to scan it using nmap's detailed scan?

**Comment by alansenairj** [comment]
![image](https://user-images.githubusercontent.com/20565821/189400351-9501d19b-af43-490d-a900-5b0a92931577.png)

**Comment by leiweibau** [comment]
If you want more Information, open one device and use the nmap scan. It is not guaranteed that nmap can determine the hostname, but the possibility exists.

When Pi.Alert has no access to the DHCP lease of the DHCP server. You have to enter the hostname manually. In case you use Pi-hole with DHCP server enabled on the same device, Pi.Alert will get the information from the server database.

When your original problem is solved, you can close this issue here. If you still have problems or questions that are not answered in the FAQ section, open an issue on my fork.

When you open the Network page once, this error disappears.

**Comment by alansenairj** [comment]
Oh man! Thank you so much. You did a really good job with this fork. 

I will put some steps here to help someone else with this problem.

1 - log with pi user always for installation
2 - curl -sSL https://github.com/leiweibau/Pi.Alert/raw/main/install/pialert_install.sh | bash
3 - in case of "RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!
" just  pip3 install --upgrade requests
4 - If you are using router's DHCP don't worry. But you MUST add your devices manually. 
5- Before you add then you need to open http:///pialertip/network.php first to avoid some errors
6-  It is done! Good luck!

![image](https://user-images.githubusercontent.com/20565821/189402403-2f7b8b3d-7d4a-4778-b3ee-685884386f9a.png)

**Comment by leiweibau** [comment]
> Is it to show me what is vendor is instead ""unknow" in this main dashbord?

No, the vendor has nothing to do with the hostnames here. The vendor DB should only help you to assign the device better.

![example](https://user-images.githubusercontent.com/105860611/189424447-c62019e9-9dac-4622-9942-8ef368b33714.jpg)

In this example the vendor name was determined from the Mac address with the help of the vendor db
