### ISSUE TITLE
MAC column in the main page is not filled

### ISSUE THREAD

**Issue by 4Arthur2** [pucherot/Pi.Alert#201]
Hello,
I have the problem, that the MAC column in the main page is not filled. When I look at the devices one by one, the MAC addresses are displayed correctly. Unfortunately not in the overview.
Does anyone have an idea?

**Comment by HCJR75** [comment]
i have the same issue , odd thing the mac shows up if i select a machine. but not when on the main dash board. 

Any one has any clues

**Comment by leiweibau** [comment]
This column is not for the MAC address, but for indicating whether the device uses a random MAC or not.

<img width="474" alt="mac-column" src="https://user-images.githubusercontent.com/105860611/196293035-e29f3349-a457-418b-8797-4659cc9a09f9.png">

**Comment by 4Arthur2** [comment]
Ok, understand. Thanks for it. 
I would appreciate to see here the MAC adresses instead of a random MAC flag.
So I close this issue.
