### ISSUE TITLE
MQTT config causing Pi.Alert not to startup

### ISSUE THREAD

**Issue by nOerkH** [pucherot/Pi.Alert#207]
Hi,

just stumbled accross Pi.Alert and I really like the idea and your work. But it seems you are not there yet ...

Just tried to setup MQTT, whenever I do so, Pi.Alert crashes and cannot boot up again.

```
# MQTT
#---------------------------
REPORT_MQTT=True
MQTT_BROKER='192.168.88.245'
MQTT_PORT=1883
MQTT_USER='mqttuser'
MQTT_PASSWORD='_$_$_$_$_$_$_$_$_'
MQTT_QOS=0
MQTT_DELAY_SEC=2
```

**Comment by jokob-sk** [comment]
Hey, it sounds you are using my fork (MQTT is only available in my fork), Please open an issue here :) https://github.com/jokob-sk/Pi.Alert

**Comment by nOerkH** [comment]
> Hey, it sounds you are using my fork (MQTT is only available in my fork), Please open an issue here :) https://github.com/jokob-sk/Pi.Alert

thank you very much for that advice - reopened: https://github.com/jokob-sk/Pi.Alert/issues/144

Issue can be closed here
