### ISSUE TITLE
DietPi

### ISSUE THREAD

**Issue by wosaa** [pucherot/Pi.Alert#21]
Hello,

unfortunately it doesn't work with DietPi, it is possible to make it compatible? 

https://github.com/MichaIng/DietPi

**Comment by pucherot** [comment]
OK, I will study this request
Thank you

**Comment by pucherot** [comment]
What problem do you have installing pi.alert with DietPi?

**Comment by wosaa** [comment]
I think the the Lighttpd setup (pre installed) is different.. I will do some test's tomorrow on my dietpi setup tomorrow.

**Comment by pucherot** [comment]
OK, thank you very much.

**Comment by pucherot** [comment]
Hello, I've made some modiffications to the installation guide.
I think that now, permits a preinstalled lighttpd.
