### ISSUE TITLE
Keep same device after change MAC and Vendor changed

### ISSUE THREAD

**Issue by webysther** [pucherot/Pi.Alert#224]
Great project, for small lab killed the netbox solution I has before.

I understand the lock device is based on MAC but to fixed new device emerging maybe a simple solution is lock device based on IP when the IP is marked as static, this will be a great progress for docker, because when creating a macvlan with[out] communication os host <--> container in the new version of compose mac address cannot be fixed anymore. I think the final step is creating a flag to make possible to mark which device I want to become ip rather mac based.

Just curious, why vendor is always updated? Make sense is automatic but when changed don't make sense anymore for my point of view.

I look around for this kind of questions, sorry if is too basic.

**Comment by leiweibau** [comment]
> Just curious, why vendor is always updated? Make sense is automatic but when changed don't make sense anymore for my point of view.

Good point.
I have adopted this suggestion for my fork.
