### ISSUE TITLE
‼️ Please note this when opening an issue ‼️

### ISSUE THREAD

**Issue by leiweibau** [pucherot/Pi.Alert#237]
If you want to open an issue, please check that you might not be using a fork or another project. If this is the case, please open this issue in the appropriate fork or project. 
It is unfair to expect a developer to monitor another fork or project to handle user issues or questions.

In addition, please note this: 
[💡➡Read before creating an issue⬅💡](https://github.com/pucherot/Pi.Alert/issues/235)

**Comment by tbkurtz** [comment]
Thanks for the heads up.
