### ISSUE TITLE
Default Behaviour for new devices

### ISSUE THREAD

**Issue by lzsix** [pucherot/Pi.Alert#238]
The Checkbox for Alert Events on New Devices keeps rechecking itself.
Is Anybody facing the same issue and already has a fix for it? 
![image](https://github.com/pucherot/Pi.Alert/assets/143028763/818fcca7-2b3b-44cf-932d-1e7f4977c28f)

**Comment by jokob-sk** [comment]
Hi, can you please close this issue an open one on the correct fork as per: https://github.com/pucherot/Pi.Alert/issues/237
