### ISSUE TITLE
Not finding devices...

### ISSUE THREAD

**Issue by adm2k** [pucherot/Pi.Alert#240]
Hello,

I am running pi.alert in a docker container on a Proxmox VM. When launched it only shows two devices. 

Any suggestions are appreciated!
![image](https://github.com/pucherot/Pi.Alert/assets/120423301/74314b83-9187-49b0-9477-961cf3965cbd)

**Comment by jokob-sk** [comment]
I thin you've opened the issue on the incorrect fork. See this for details: https://github.com/pucherot/Pi.Alert/issues/235 

Please close this issue.
