### ISSUE TITLE
Installation issue on Ubuntu 

### ISSUE THREAD

**Issue by Marsupoil76** [pucherot/Pi.Alert#248]
can't initiat fitst step on Ubuntu 
curl -sSL https://github.com/pucherot/Pi.Alert/raw/main/install/pialert_install.sh | bash
--------
syruce@pialerte:~$ sudo curl -sSL https://github.com/pucherot/Pi.Alert/raw/main/install/pialert_install.sh | bash

############################################################
 Pi.Alert Installation
############################################################
Fri Jan 19 14:20:33 UTC 2024
Logfile: pialert_install_2024-01-19_14-20.log

************************************************************
************************************************************
**            ERROR INSTALLING PI.ALERT                   **
************************************************************
************************************************************

Logs result : 

############################################################
 Pi.Alert Installation
############################################################
Fri Jan 19 14:20:51 UTC 2024
Logfile: pialert_install_2024-01-19_14-20.log

**Comment by jokob-sk** [comment]
Please note that your issue will probably not be actioned. Look at https://github.com/pucherot/Pi.Alert/issues/235 and https://github.com/pucherot/Pi.Alert/issues/237

**Comment by Marsupoil76** [comment]
Thks Dude for the reply :)
