### ISSUE TITLE
Many, many new devices named Null

### ISSUE THREAD

**Issue by WeterPeter** [pucherot/Pi.Alert#249]
![Screenshot 2024-01-30 at 11 54 49](https://github.com/pucherot/Pi.Alert/assets/52879850/e2b5f21b-848c-42e7-86e7-4aa224d6e46e)

I run Pi.Alert for several weeks now in Docker on a Synology NAS and for the past day or so I gat an increase from about 80 devices to over 2700! All of the added devices with name null.

![Screenshot 2024-01-30 at 11 57 58](https://github.com/pucherot/Pi.Alert/assets/52879850/c35a28fe-8e05-4ee2-87e7-32564e895642)

What could be wrong?

**Comment by jokob-sk** [comment]
Look at https://github.com/pucherot/Pi.Alert/issues/235 and https://github.com/pucherot/Pi.Alert/issues/237

please close this issue after you've submitted it to the correct fork

**Comment by WeterPeter** [comment]
closed
