### ISSUE TITLE
Email alert spams me..

### ISSUE THREAD

**Issue by iroQuai** [pucherot/Pi.Alert#25]
I've set up email alert. I've marked two devices as "notify when down". I did this last night and went to bed. This morning I have 30+ emails from pi.alert, mentioning every change in the network. This is both too much as unrequested information.

Is there a way to turn this off? Or maybe get one excerpt every day? I've disabled the email alerts for now..

**Comment by theniwo** [comment]
you can set "Skip repeated notifications during: X Hours"
like described [Here](https://github.com/pucherot/Pi.Alert/blob/main/docs/DEVICE_MANAGEMENT.md#events--alerts-config)

**Comment by iroQuai** [comment]
I thought this was a setting per device. I get noticed about every device in the network that sleeps or get disconnected for a short moment. I've changed the setting you mentioned for one device now, lets see...

**Comment by theniwo** [comment]
Altneratively you could set the scan cycle for that devices to 15 or increase the cronjob interval.

**Comment by pucherot** [comment]
Be careful, changing the crontab should be consistent with the definition of the cycles that are internally in the "ScanCycles" table of the database

**Currently, only cycles 0, 1, & 15 are active.**

### Table defenition:
![image](https://user-images.githubusercontent.com/25605499/104596336-27459a00-5674-11eb-8275-f68b2645ec46.png)

### Table Content:
![image](https://user-images.githubusercontent.com/25605499/104596471-4e9c6700-5674-11eb-9d2a-2fc91a67bf77.png)
