### ISSUE TITLE
Scan multiple VLAN does not work

### ISSUE THREAD

**Issue by Tuxtom007** [pucherot/Pi.Alert#252]
Hello,

my PiAlert is installed as Linux-Container on Proxmox ( LXC )
default Network:  eth0  

The scan of the default network alone works

Then I assigned several network interfaces to the LXC, one for each VLAN to be scanned with the corresponding VLAN ID and a fixed IP in the VLAN
Then I entered the corresponding networks in pialert.conf and the scan no longer works or only the last VLAN in the list is scanned.
 
I have tried the following settings, but none of them work:

`
SCAN_SUBNETS      = [ '10.0.90.0/24 --interface=eth0 --vlan=90', '10.0.10.0/24 --interface=eth1 --vlan=10', '10.0.20.0/24 --interface=eth2 --vlan=20', '10.0.30.0/24 --interface=eth3 --vlan=30' ]

SCAN_SUBNETS      = [ '--interface=eth0', '--interface=eth1', '--interface=eth2', '--interface=eth3' ]

SCAN_SUBNETS      = [ '10.0.90.0/24', '10.0.10.0/24', '10.0.20.0/24', '10.0.30.0/24' ]
`

An arp-scan works on the machine for all VLANs and returns the expected results:

`arp-scan 10.0.10.0/24 --interface=eth1`

I then found the following in the log file

`
Pi.Alert 3.02 (2021-04-24)
---------------------------------------------------------
Scan Devices
    ScanCycle: 15
    Timestamp: 2024-02-27 15:00:00
-------------------->  2024-02-27 15:00:01.250125   0:00:00.000031   Query ScanCycle confinguratio
n...
-------------------->  2024-02-27 15:00:01.250138   0:00:00.000013   Opening DB...
-------------------->  2024-02-27 15:00:01.250569   0:00:00.000431   Closing DB...

Scanning...
    arp-scan Method...
-------------------->  2024-02-27 15:00:01.250611   0:00:00.000042   arp-scan starts...
Traceback (most recent call last):
  File "/root/pialert/back/pialert.py", line 1488, in <module>
    sys.exit(main())       
             ^^^^^^
  File "/root/pialert/back/pialert.py", line 85, in main
    res = scan_network()
          ^^^^^^^^^^^^^^
  File "/root/pialert/back/pialert.py", line 361, in scan_network
    arpscan_devices = execute_arpscan (arpscan_retries)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pialert/back/pialert.py", line 451, in execute_arpscan
    subnets = SCAN_SUBNETS.strip().split()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'strip'
`

The question now is, what am I doing wrong in the config?
I have to enter other VLANs that should also be scanned

Thanks in advance
Thomas

**Comment by jokob-sk** [comment]
Hi there, please close this issue as it's not opened on the correct fork. See info here: https://github.com/pucherot/Pi.Alert/issues/235
