### ISSUE TITLE
Fake IP change

### ISSUE THREAD

**Issue by purplepotables** [pucherot/Pi.Alert#253]
I have looked and haven't been able to find a similar issue. I have a pi alert instance in an lxc. It works pefectly except it is reporting that a google nest hub that I have given a static ip to outside of my dhcp range is changing to the broadcast address (X.X.X.75 to X.X.X.255 on a /24 network). It will report the change, then report it changed back on the next scan. It will sometimes do it several times an hour and sometimes be fine for 12+ hours. There is nothing in my router/dchp logs that lead me to believe it is actually giving that address. Can anyone explain what is happening here?

**Comment by jokob-sk** [comment]
Please have a look at https://github.com/pucherot/Pi.Alert/issues/235 and https://github.com/pucherot/Pi.Alert/issues/237

If you are using a different fork, please close this issue after you've submitted it to the correct one.

**Comment by jokob-sk** [comment]
Hi @purplepotables, can you close this issue to keep the main notifications on the top? thanks

**Comment by purplepotables** [comment]
Closing issue.
