### ISSUE TITLE
SCAN_SUBNETS not limiting much?

### ISSUE THREAD

**Issue by unlucio** [pucherot/Pi.Alert#254]
I'm new to pi alert, after installing it I noticed it didn't pick up only my devices but a ton of docker containers:

<img width="1523" alt="Screenshot_2024-03-25_at_19_50_18" src="https://github.com/pucherot/Pi.Alert/assets/778799/b7b54a66-514c-4e66-be65-b8ec282e8ee7">

and most of them are offline anyway (docker swarm and kube might move stuff around):
<img width="532" alt="Screenshot 2024-03-25 at 19 56 54" src="https://github.com/pucherot/Pi.Alert/assets/778799/1f42407d-ee17-4a60-8ade-7d6c4a6264a3">

in this issue: https://github.com/pucherot/Pi.Alert/issues/15
is explained how `SCAN_SUBNETS` might be the solution I was looking for, but setting it to:
```
SCAN_SUBNETS=['10.6.9.10/24 --interface=eth0']
```
<img width="336" alt="Screenshot 2024-03-25 at 19 53 22" src="https://github.com/pucherot/Pi.Alert/assets/778799/d897beef-76e8-4d75-995a-5475fdb76f92">

doesn't seem to help.

I've pages full of `null` devices making the UI quite sluggish, what's the best way to get rid of them?

**Comment by unlucio** [comment]
Errata Corigere: I noticed I set `10.6.9.10/24` and I changed it to `10.6.9.0/24`, although I doubt it mattered much as the 24bit subnet would still match anything from 1 to 254

**Comment by leiweibau** [comment]
Please look at https://github.com/pucherot/Pi.Alert/issues/237 and https://github.com/pucherot/Pi.Alert/issues/235 and close this issue
