### ISSUE TITLE
Question about offline showing devices 

### ISSUE THREAD

**Issue by hansw1204** [pucherot/Pi.Alert#255]
Why is my Pialert showing devices as offline that are clearly online, like my gateway router and numerous other devices?
Can I do anything to make the reporting more accurate?
Many thanks for any help!

**Comment by jokob-sk** [comment]
Hey @hansw1204 ,

Please check https://github.com/pucherot/Pi.Alert/issues/235 and https://github.com/pucherot/Pi.Alert/issues/237 and close this issue. Thanks!

**Comment by hansw1204** [comment]
Sorry!

From: jokob-sk ***@***.***>
Date: Wednesday, April 10, 2024 at 17:04
To: pucherot/Pi.Alert ***@***.***>
Cc: HaWi ***@***.***>, Mention ***@***.***>
Subject: Re: [pucherot/Pi.Alert] Question about offline showing devices (Issue #255)

Hey @hansw1204<https://github.com/hansw1204> ,

Please check #235<https://github.com/pucherot/Pi.Alert/issues/235> and #237<https://github.com/pucherot/Pi.Alert/issues/237> and close this issue. Thanks!

**Comment by jokob-sk** [comment]
all good, can you close this issue to keep the main notifications on the top? thanks
