### ISSUE TITLE
docker folders not accessible

### ISSUE THREAD

**Issue by Kilkenny-82** [pucherot/Pi.Alert#256]
Recently I updated my docker container with PiAlert, this caused it to become Net Alert, which required some setting changes etc. And the first advice was to create a backup, now truthfully, I haven't gotten to creating external backups, so haven't run into this issue sooner. But the folders (config and db) can't be accessed. In SSH it says I can't cd into the folder, if I try CHMOD the folder it says it doesn't exist and using Samba I also can't access the folders.

But since I haven't been running for so long and made a few setup mistakes I decided to just create new folders and start over. And so I did, folders accessible and empty, changed the folders in my Docker-Compose file and started the container. But now these folders are also no longer accessible, what am I doing wrong?

I'm running the container with a few others on OpenMediaVault, the other containers have no issues with access. My Net Alert is on v24.4.17.

**Comment by jokob-sk** [comment]
Please close this issue and open it at the correct github repo. Look at https://github.com/pucherot/Pi.Alert/issues/235 and https://github.com/pucherot/Pi.Alert/issues/237
