### ISSUE TITLE
Error when looking for Rogue DHCP

### ISSUE THREAD

**Issue by sgr78** [pucherot/Pi.Alert#257]
Hello,
Maybe It's me, I may have something overlooked, configuration issue or Is it PiAlert issue, here it goes.
I'm having this Issue a long time (six months or more and still researching It)..
I have two Instances of PiAlert one for production and one for tests, 
The first Instance is a VM with no Issues at all and the second one is a bare deploy on a Pi 5 with Pi OS Lite,
On the Pi 5 I have two IF, Eth0 and Wlan0 which are actively connected for redundancy,
with preset ip pool based on mac address from my main router, yet Pi device is set to AUTO and sends request properly and gets offer..

The Issue is when the Rogue DHCP runs I always get on the Pi 5
```
Looking for Rogue DHCP Servers...
    Detection Error
```
I have ran
and concluded sucessfuly with no errors at all
```
nmap --script broadcast-dhcp-discover
nmap --script broadcast-dhcp-discover -e eth0
nmap --script broadcast-dhcp-discover -e wlan0
dhclient -d -nw eth0
dhclient -d -nw wlan0
ip route | grep default
```
I also peeked at the source code of pialert on the Rogue DHCP Section and ran
`nmap --script broadcast-dhcp-discover 2>/dev/null | grep "Server Identifier" `
Which also concluded successfully and returned as expected two Server Identifiers because of Eth and Wlan 
(with same DHCP server IP, as it is connected on the same network)

Yes I have tried disabling one of the two IF, just to test if the Issue is caused by multiple enabled IF with multiple DHCPs (even though it is the same server on both) but no dice...

I'm running out of Ideas here and any help/guidance will be much welcomed and appreciated!

**Comment by jokob-sk** [comment]
Please close this issue and open it at the correct github repo. Look at https://github.com/pucherot/Pi.Alert/issues/235 and https://github.com/pucherot/Pi.Alert/issues/237

**Comment by sgr78** [comment]
Ditto, Thx!
