### ISSUE TITLE
Network section unmanaged switch uplinks 

### ISSUE THREAD

**Issue by huuscript** [pucherot/Pi.Alert#258]
When pointing “router” to unmanaged “switch” created in “Network” section, there is no way to specify the origin port back in the router. eg Uplink to target “switch” port 6, port 6 on the “switch” is occupied by “router” bit back on router all ports are still free. When setting target “router” from the switch, i can only specify the local port not the target port, so router ports still unoccupied. 

With this behaviour, I can not link two unmanaged switch together in “network” section as well.

There must me something i miss?

**Comment by jokob-sk** [comment]
Please close this issue and open it at the correct github repo. Look at https://github.com/pucherot/Pi.Alert/issues/235 and https://github.com/pucherot/Pi.Alert/issues/237

**Comment by leiweibau** [comment]
From the docs:

>**Attention:
Switches (e. g. unmanaged switches) or Routers which do not appear in the devices list cannot be assigned to any other network component, not even via the "manual port configuration".**

Please close this issue here
Thx

**Comment by huuscript** [comment]
Opps i didnt realuse i post in the wrong fork. Thank you leiweibau for continuing to maintain it ❤️. since then i have come up with a work around which work quite well just in case anyone come across this post. if you have proxmox. creat a container and let pialert detect that. now its have a mac and use that as the switch and turn off (0) scan cycle to stop it from scanning it, then you can delete your container …
