### ISSUE TITLE
Remember "Show XXX entries" dropdown value or change default to larger than 10

### ISSUE THREAD

**Issue by jasonwtobe** [pucherot/Pi.Alert#26]
My preferred view (for this and PiHole) is always "show 100 entries" so I know I'm seeing all entries in the result table below and never see pagination. PiAlert doesn't seem to remember this chosen value when navigating through different PiAlert URL's or on initial load. 

Can this value be remembered or a larger default (eg. 100) be used?

**Comment by pucherot** [comment]
OK, I will implement this request
Thank you

**Comment by eugef66** [comment]
I second this request. 
I currently modified devices.php and index.php to remove "pagination" completely, 

  $('#tableDevices').DataTable({                                                                                                                                                                                               'paging'      : false,           

however I know it will be overwritten with next update. Would be good to have page remember my choice or make the page size configurable in ".config"

**Comment by pucherot** [comment]
Done.
Will be available in next version.
