### ISSUE TITLE
Service fails to start due to Apache2 / Lighttpd conflict

### ISSUE THREAD

**Issue by dustingrady** [pucherot/Pi.Alert#260]
The GUI seems to be unreachable, and when looking at the service list I see that Apache2 has failed to start due to a conflict on port 80, as it is already "in use" by Lighttpd.

Stopping Lighttpd allows Apache2 to start, but then Lighttpd cannot. Things had worked fine for quite some time and this recently began happening. Not sure if this is a regression or a one off.

**Comment by jokob-sk** [comment]
Please make sure you opened this at the right fork. The original PiAlert is unmaintained. If so, please close this issue and open it at the correct github repo. Please have a look at https://github.com/pucherot/Pi.Alert/issues/235 and https://github.com/pucherot/Pi.Alert/issues/237
