### ISSUE TITLE
Where do I enable dnsmasq scanning?

### ISSUE THREAD

**Issue by cwmoriarty** [pucherot/Pi.Alert#262]
[Documentation](https://github.com/pucherot/Pi.Alert?tab=readme-ov-file#scan-methods)  suggests compatibility with dnsmasq. I don't run PI Hole (I run Kea + Unbound) -- nothing is obvious in the config file.

**Comment by jokob-sk** [comment]
Please make sure you opened this at the right fork. The original PiAlert is unmaintained. If so, please close this issue and open it at the correct github repo. Please have a look at https://github.com/pucherot/Pi.Alert/issues/235 and https://github.com/pucherot/Pi.Alert/issues/237

**Comment by cwmoriarty** [comment]
Thanks @jokob-sk

**Comment by cwmoriarty** [comment]
Thanks @jokob-sk
