### ISSUE TITLE
Scan range (or similar) for VLAN support

### ISSUE THREAD

**Issue by jasonwtobe** [pucherot/Pi.Alert#27]
I use VLAN's for network segregation between IOT and other devices. IOT is `192.168.99.0/24` and "main" network is `192.168.10.0/24` (as well as others). There are firewall rules between the VLAN's to allow access from devices in main (where the Pi lives) to IOT for DNS, SSH, etc. 

It would be great if a scan range could be set for PiAlert (eg. `192.168.10.0/24` and `192.168.99.0/24`) so that it can monitor both VLAN's.

**Comment by pucherot** [comment]
Duplicated. Request #19
