### ISSUE TITLE
Read only database

### ISSUE THREAD

**Issue by pucherot** [pucherot/Pi.Alert#3]
Looks like there is still an issue in the database.
`attempt to write a readonly database`

_Originally posted by @ncmoud in https://github.com/pucherot/Pi.Alert/issues/2#issuecomment-758017261_

**Comment by ncmoud** [comment]
Thanks for moving that.

**Comment by pucherot** [comment]
Please, can you send the output of this command?
~~~
ls -l ~/pialert/db
~~~

**Comment by ncmoud** [comment]
![image](https://user-images.githubusercontent.com/40201919/104202208-e73fa680-542a-11eb-92db-36cb98b641f2.png)

**Comment by ncmoud** [comment]
Okay, just referenced my Linux textbook and it looks to me like only the "pi" user can write to the database. I'm guessing Pi.Alert is either trying to write from another group or as a stranger.

**Comment by ncmoud** [comment]
Looks like the following solution did the trick.
```
sudo chgrp -R www-data ~/pialert/db
chmod -R 770 ~/pialert/db
```
760 means the site can't load the database because the group misses the permission to execute the file.

**Comment by pucherot** [comment]
Exactly. We must grant permissions to the user who runs the Lighttpd web server.
There are 2 possibilities

### 1
~~~
chmod -R 766 ~/pialert/db
~~~
### 2
~~~
sudo chgrp -R www-data ~/pialert/db
chmod -R 760 ~/pialert/db
~~~

I think both are valid.

**Comment by ncmoud** [comment]
I used number 2 with a slight modification, using 770 instead of 760. The group was missing the permission to execute. It works now.
![image](https://user-images.githubusercontent.com/40201919/104205016-2fac9380-542e-11eb-9600-2efa4e784331.png)

**Comment by pucherot** [comment]
Perfect, so is necessary +x permissions:

### 1
~~~
chmod -R 777 ~/pialert/db
~~~
### 2
~~~
sudo chgrp -R www-data ~/pialert/db
chmod -R 770 ~/pialert/db
~~~

BR

**Comment by ncmoud** [comment]
Thanks for the help. I wouldn't have been able to easily figure out what the group name of the webserver is. I was already half guessing this was a permission issue.

**Comment by pucherot** [comment]
Install process updated.

For your comfort, add a pi.alert DNS Record:

Pi-hole -> Local DNS -> DNS Records -> Add new domain /IP:
  - Domain; pi.alert
  - IP Address: 192.168.1.x (replace the 192.168.1.x with your Raspberry IP)
  - Press "Add"

With this trick, you can use http://pi.alert/ instead of http://pi.hole/pi.alert/

**Comment by ncmoud** [comment]
![image](https://user-images.githubusercontent.com/40201919/104208646-05a8a080-5431-11eb-8b38-a2c69a1c81a6.png)
Nope. also, it's http://pi.hole/pialert

**Comment by pucherot** [comment]
Please, check issue #4
