### ISSUE TITLE
Status changed from new to online/offline only after changing the view period to today

### ISSUE THREAD

**Issue by theniwo** [pucherot/Pi.Alert#31]

**Comment by pucherot** [comment]
This option is not "view period", is not a filter. As the label says is **"New device period"** 
**How long ago you consider the devices added since then are new**

![image](https://user-images.githubusercontent.com/25605499/104700491-865aeb80-5714-11eb-8623-4e3efbce256c.png)

**Comment by theniwo** [comment]
Aye, It would be great if the default was today, so the list of devices would show the actial online/offline status instead of new for all devices

**Comment by pucherot** [comment]
In a month all these devices will be "NOT NEW" in the default view.
however, I will study how to add a functionality that allows saving the state of the last selection in the combobox.

**Comment by theniwo** [comment]
It would be better if we could acknowledge a device as known instead of having to wait a month

**Comment by pucherot** [comment]
Yes, it's another possibility.

**Comment by eugef66** [comment]
I second this request. There should be a way to mark devices as "known", so they never shown as "new".

**Comment by eugef66** [comment]
I noticed you tagged this change with "help wanted". I can help with development if you agree/finalize  the approach.

**Comment by pucherot** [comment]
done.
Available in next version,
