### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by oreillygshane** [pucherot/Pi.Alert#35]
I reran the install and it wiped all previous setup and records

Is there a cleaner way to update?

curl -LO https://github.com/pucherot/Pi.Alert/raw/main/install/pialert_latest.tar
tar xvf pialert_latest.tar
rm pialert_latest.tar

**Comment by MaleNurse** [comment]
at the moment, I think you need to backup db/pialert.db and back/pialert.conf before running the above commands, then move them back when done.

**Comment by pucherot** [comment]
Exactly, but this versions are only bugfixing, if you don't have problems is not necessary to udpdate.
In the future, will be a update script.

**Comment by pucherot** [comment]
Done.
New **update Pi.Alert** process created.
