### ISSUE TITLE
'QUERY_MYIP_SERVER' not defined error

### ISSUE THREAD

**Issue by MaleNurse** [pucherot/Pi.Alert#36]
python pialert.py internet_IP return the following error:

Pi.Alert 2.52 (2021-01-11)
---------------------------------------------------------
Check Internet IP
    Timestamp: 2021-01-16 09:52:00

Retrieving Internet IP...
Traceback (most recent call last):
  File "pialert.py", line 1369, in <module>
    sys.exit(main())
  File "pialert.py", line 76, in main
    res = check_internet_IP()
  File "pialert.py", line 110, in check_internet_IP
    internet_IP = get_internet_IP()
  File "pialert.py", line 170, in get_internet_IP
    curl_args = ['curl', '-s', QUERY_MYIP_SERVER]
NameError: name 'QUERY_MYIP_SERVER' is not defined

**Comment by pucherot** [comment]
You have updated `pialert.py` but not `pialert.conf`.
please, add ` QUERY_MYIP_SERVER = 'http://ipv4.icanhazip.com'` into `pialert.conf` file
This versions are only bugfixing, is not necessary to update if you don't have problems.

**Comment by pucherot** [comment]
New **update Pi.Alert** process created.
