### ISSUE TITLE
Feature request: Mass/batch edit devices

### ISSUE THREAD

**Issue by MaleNurse** [pucherot/Pi.Alert#37]
My network has about 50 items and it would be nice to be able to change details of groups of similar devices all at once as opposed to one at a time.

**Comment by pucherot** [comment]
I will study this request
Perhaps int the future I'll develop this feature.
Thank you

**Comment by pucherot** [comment]
Done.

Available in next version.

![image](https://user-images.githubusercontent.com/25605499/115517765-c5ef2180-a287-11eb-8d69-8bb9c4fc5c7e.png)
