### ISSUE TITLE
Feature Request: Remove conf and db files from install

### ISSUE THREAD

**Issue by MaleNurse** [pucherot/Pi.Alert#38]
Removing non-static files from the install TARs would make updating much easier. For those doing initial installs, additional curl or wget commands (or a script containing them) could be used to download them to the correct location.

**Comment by pucherot** [comment]
at the moment, new versions are only bugfixing. Is not necessary to update if you don't have problems.
In the future will be available an update script.

**Comment by pucherot** [comment]
Done
