### ISSUE TITLE
Feature Request: remove versioning info from pyalert.conf

### ISSUE THREAD

**Issue by MaleNurse** [pucherot/Pi.Alert#39]
Since this is a user-modified file, it it needs to be preserved. When it is, the correct version is not displayed on the site.

**Comment by pucherot** [comment]
at the moment, new versions are only bugfixing. Is not necessary to update if you don't have problems.
In the future will be available an update script.

**Comment by pucherot** [comment]
Done
New **update Pi.Alert** process created.
