### ISSUE TITLE
"Error updating device" where name contains quote character

### ISSUE THREAD

**Issue by jasonwtobe** [pucherot/Pi.Alert#42]
Pi.alert  2.52  (2021-01-11)

On the device info page (`/pialert/deviceDetails.php?mac=<MAC>`) where you can update the name etc of a device, if you enter a quote `"` you get an error on save. See example below where `name` includes a single `"`

![image](https://user-images.githubusercontent.com/48776255/104920818-b0244480-5998-11eb-85aa-304ba63051dd.png)

**Comment by pucherot** [comment]
Thanks. At the moment, you can use single quotes.
In future version this issue will be solved.

**Comment by sml156** [comment]
It seems that quotes are not valid character, Check out the RFC 

https://man7.org/linux/man-pages/man7/hostname.7.html
This is something you probably should not fix

**Comment by pucherot** [comment]
Solved in next version

**Comment by jasonwtobe** [comment]
🙌
