### ISSUE TITLE
Client names not resolving

### ISSUE THREAD

**Issue by jasonwtobe** [pucherot/Pi.Alert#43]
Pi.Alert  2.60  (2021-01-20).

Client names are not resolving, instead shows `(unknown)` for all clients except Router. 

![pialert](https://user-images.githubusercontent.com/48776255/105517196-082fb380-5cd7-11eb-9603-b2aa3cdb28cc.png)

No PiHole setup on the VM which runs Pi.Alert (PiHole on it's own Pi), this may be something to do with it as my previous installation was on same Pi as PiHole with `PIHOLE_ACTIVE   = True` in `/pialert/config/pialert.conf` and names resolved as expected. Can post more install info if needed. 

Clients names resolve on other devices/apps on network (Fing mobile app on iOS, Angry IP scanner on Windows, etc), Pi.Alert seems to be the only one which doesn't resolve.

**Comment by atylmo** [comment]
Same here, with 2.61. Also running it in a VM with a separate physical Pi-hole.

**Comment by Rippernz** [comment]
Im getting the same on 2.61 with PiAlert running on the same Pi as PiHole.

PiHole resolves names

**Comment by pucherot** [comment]
At the moment Pi.Alert don't have device name resolution. 
Now, it only uses the device names identified by Pi.Hole and DHCP server (dnsmasq).
In the future, Pi.Alert will include a resolution name.

BR

**Comment by jasonwtobe** [comment]
Many thanks for the update. Looking forward to it! 🥳

**Comment by pucherot** [comment]
Added Device name resolution using Reverse DNS in your LAN
If you don't have a local DNS server (Pi-hole, router u other) the device name can't be resolved.
This feature will be available in next version.
