### ISSUE TITLE
Please provide documentation for updating Pi-Alert to newer versions.

### ISSUE THREAD

**Issue by stonefrango** [pucherot/Pi.Alert#45]
As mentioned in the title, I would like request that update/upgrade documentation be provided under the README.md or existing INSTALL.md documentation or in its own new document.

I apologize if I should have an existing understanding of how to update these sorts of things when I initially CURL them and set them up, as I am still self-teaching on using things like Linux and Github, but as far as I can see there is no clear documentation for updating Pi.Alert (particularly when running it beside Pi-hole). 

I tried updating by starting from step 5.1 in the INSTALL.md and ended up breaking both my pi-hole and pi-alert web interfaces (but that's not the subject of this Issue), so for the sake of other Pi.Alert users and myself I would like to request instructions on what steps are supposed to be followed for updating Pi.Alert.

**Comment by pucherot** [comment]
Done
New **update Pi.Alert** process created.
