### ISSUE TITLE
Could not obtain IP on interface eth0 (bridged eth0)

### ISSUE THREAD

**Issue by ruiasamaro27** [pucherot/Pi.Alert#47]
On the installation, the process gives a error:

"WARNING: Could not obtain IP address for interface eth0. Using 0.0.0.0 for the source address, which is probably not what you want."

I believe this happens because eth0 is actually bridged to tap0 creating the default interface br0 (not recognized on the installation). Without the correct interface or IP it won't execute the arp-scan method.

![Screenshot 2021-01-26 225345](https://user-images.githubusercontent.com/78053848/105916779-5c190000-6029-11eb-9cc4-db48b421907e.png)

**Comment by pucherot** [comment]
Can you execute this command?

`sudo arp-scan -l"

**Comment by ruiasamaro27** [comment]
Just did. Same error:
![Screenshot 2021-01-27 122148](https://user-images.githubusercontent.com/78053848/105990340-3ed04a00-609a-11eb-9fd8-dde0bb9bc007.png)

**Comment by pucherot** [comment]
have you connect your Raspberry to your LAN or WIFI?

**Comment by ruiasamaro27** [comment]
To my LAN. 
I believe the main problem is that its is a bridged connection (the pic explains). Since I needed a bridged VPN, the eth0 was bridged with tap0 (VPN interface) and created the interface **br0** (eth0 + tap0). 

Everything works exactly as expected, the only "problem" is that pi.alert can't find an IP on eth0 because it doesn't have one. The IP is on br0 (192.168.1.4).

eth0 is the LAN interface
tap0 is the OpenVPN interface
br0 is the bridged connection (eth0 + tap0)
wg0 is wireguard VPN interface
![Screenshot 2021-01-27 124713](https://user-images.githubusercontent.com/78053848/105993283-19ddd600-609e-11eb-9b62-4c55df0139b1.png)

**Comment by pucherot** [comment]
please try:
`sudo arp-scan --interface br0 -l`

**Comment by ruiasamaro27** [comment]
Perfect! It worked!

Should I create a chron entry? Or is there an option to automate this command instead of the default one?

**Comment by pucherot** [comment]
At the momment it's not possible configure this options in Pi.Alert.
Now, you can patch Pi.Alert with this command:
`sed -i "s/arpscan_args \= \['sudo', 'arp-scan'/arpscan_args \= \['sudo', 'arp-scan', '--interface=br0'/g" ~/pialert/back/pialert.py`

I the future this option may be configured directly with Pi.Alert.

**Comment by ruiasamaro27** [comment]
Thanks you!
Appreciate the help!
