### ISSUE TITLE
Question - Separate Web Panel

### ISSUE THREAD

**Issue by tombermon** [pucherot/Pi.Alert#49]
I noticed several individuals stating this is supposed to work along side of Pi-Hole.  Is this a separate Web Panel / port being used or does this directly integrate with the Pi-Hole interface?

**Comment by mssteuer** [comment]
See installation guide where the creator explains how to set this up alongside pi.hole.

**Comment by pucherot** [comment]
Hi. You can use Pi.Alert in combination with Pi-hole without problems.
Each application will have its own independent web panel served by the same webserver.
