### ISSUE TITLE
Error updating device

### ISSUE THREAD

**Issue by Mannaek** [pucherot/Pi.Alert#51]
When i try to rename a device i get this error:

> Error updating device
> 
> UPDATE Devices SET
>                  dev_Name            = "TP Link",
>                  dev_Owner           = "(unknown)",
>                  dev_DeviceType      = "Router",
>                  dev_Vendor          = "TP-LINK TECHNOLOGIES CO.,LTD.",
>                  dev_Favorite        = "0",
>                  dev_Group           = "(unknown)",
>                  dev_Comments        = "",
>                  dev_StaticIP        = "0",
>                  dev_ScanCycle       = "1",
>                  dev_AlertEvents     = "1",
>                  dev_AlertDeviceDown = "0",
>                  dev_SkipRepeated    = "0"
>           WHERE dev_MAC="a4:2b:b0:d9:09:a9"\n\nunable to open database file

DHCP server is on an ASUS router
Pihole and Pi Alert is on a PRi 3b+

**Comment by pucherot** [comment]
What king of installation have you done: manual or one-step?

**Comment by Mannaek** [comment]
> What king of installation have you done: manual or one-step?

One step, the one from Reddit

**Comment by pucherot** [comment]
please, can you exectute this commands?
`ls -l ~/pialert`
`ls -l ~/pialert/db`

**Comment by pucherot** [comment]
hi, any news?

**Comment by Mannaek** [comment]
Hi,

Yeah i reinstalled the app and it works. The only issue I have is that it says my Pi-hole is down when it isn’t. Will sent you a screenshot when I’m at home

**Comment by pucherot** [comment]
Please, can you send me the screeshot?
thx

**Comment by eugef66** [comment]
Just some info that may help investigating this issue
I got this error once and it stated at the end of the message  "database is locked". 
I assumed cron job was running at the time and locked db for updates. I waited a minute and pressed Save again and it was sent successfully.
