### ISSUE TITLE
Database is Read Only

### ISSUE THREAD

**Issue by dcdavis4** [pucherot/Pi.Alert#55]
On initial configuration, I was able to make modifications to the database.  I ran the update command and found that the database had become read only.  I do not see a command to restart the database.  This message was displayed in a pop-up in the browser when making an edit to a device.

UPDATE Devices SET
                 dev_Name            = "DEVICENAME",
                 dev_Owner           = "House",
                 dev_DeviceType      = "",
                 dev_Vendor          = "VENDOR",
                 dev_Favorite        = "0",
                 dev_Group           = "Others",
                 dev_Comments        = "",
                 dev_StaticIP        = "0",
                 dev_ScanCycle       = "1",
                 dev_AlertEvents     = "1",
                 dev_AlertDeviceDown = "0",
                 dev_SkipRepeated    = "0"
          WHERE dev_MAC="MACADDR"\n\nattempt to write a readonly database

**Comment by dcdavis4** [comment]
I was able to clear the issue by running the update_vendors command: python ~/pialert/back/pialert.py update_vendors.

Re-running the permissions change did not resolve the issue.

**Comment by pucherot** [comment]
ohh, sorry. Is a bug in the update process.

Solved.
Please, execute the update process again.
