### ISSUE TITLE
Over 8000 Devices 

### ISSUE THREAD

**Issue by elbrato** [pucherot/Pi.Alert#58]
Where does PiAlert gets the devices from?
I have 2 Piholes, one Main and one as a Backup. On my Main Pihole Pialert says i have 8939 Devices, the Second Pialert shows 26 Devices.

**Comment by pucherot** [comment]
8939 Devices? wooow

- Can you check who many devices do you have inboth  Pi-hole?
Pi-hole admin portal -> Tools -> Network -> "Showing 1 to 10 of XX entries" (at the bottom)

- Do you have DHCP enabled in any of the two Pi-hole?

**Comment by elbrato** [comment]
On my Main Pihole it shows at the moment zero devices, because i flushed my Network Table.
My Second Pihole has 21 Devices but these 5 more on PiAlert are no Problem for me.

No DHCP ist not enabled on any of these two.

**Comment by elbrato** [comment]
I solved it by flushing the Network Table and an re-install of PiAlert.

**Comment by pucherot** [comment]
Perfect
