### ISSUE TITLE
libwww-perl error during update

### ISSUE THREAD

**Issue by matt70tx** [pucherot/Pi.Alert#59]
Got this error when I ran update. Fixed by by running "sudo apt-get install libwww-perl"

Pi.Alert 2.61 (2021-01-25)
---------------------------------------------------------
Update HW Vendors
    Timestamp: 2021-01-27 09:55:00

Updating vendors DB (iab & oui)...
Can't locate LWP/UserAgent.pm in @INC (you may need to install the LWP::UserAgent module) (@INC contains: /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/arm-linux-gnueabihf/perl5/5.28 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/arm-linux-gnueabihf/perl-base) at /usr/sbin/get-iab line 36.
BEGIN failed--compilation aborted at /usr/sbin/get-iab line 36.
Can't locate LWP/UserAgent.pm in @INC (you may need to install the LWP::UserAgent module) (@INC contains: /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/arm-linux-gnueabihf/perl5/5.28 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/arm-linux-gnueabihf/perl-base) at /usr/sbin/get-oui line 31.
BEGIN failed--compilation aborted at /usr/sbin/get-oui line 31.
Traceback (most recent call last):
  File "/home/dietpi/pialert/back/pialert.py", line 1376, in <module>
    sys.exit(main())
  File "/home/dietpi/pialert/back/pialert.py", line 83, in main
    res = update_devices_MAC_vendors('-s')
  File "/home/dietpi/pialert/back/pialert.py", line 265, in update_devices_MAC_vendors
    update_output = subprocess.check_output (update_args)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['sh', '/home/dietpi/pialert/back/update_vendors.sh', '-s']' returned non-zero exit status 2

- Testing Pi.Alert Internet IP Lookup...

Pi.Alert 2.61 (2021-01-25)
---------------------------------------------------------

**Comment by pucherot** [comment]
please, try to execute this command:
`sudo curl -O http://standards-oui.ieee.org/iab/iab.csv`

**Comment by pucherot** [comment]
hi. any news?

**Comment by pucherot** [comment]
unanswered
