### ISSUE TITLE
Strange mixture of IPs generated for the pi.alert

### ISSUE THREAD

**Issue by JosefWaida** [pucherot/Pi.Alert#60]
Hi,
I am getting a weird mixture of generated IPs, somehow mixed together to serve an IP for pi.alert. 
```
------------------------------------------------------------
 Installation process finished
------------------------------------------------------------
Use: - http://pi.alert/
     - http://192.168.0.10910.6.0.1172.18.0.1172.17.0.1169.254.136.215169.254.226.5/pialert/
To access Pi.Alert web
```

This seems to mix my rpi's IP with what seems like docker (virtual) IPs. 
I would just use the pi.alert, however these names do not work well on windows (rpi is my dns, not a dhcp server)
Looking at pialert_install_2021-01-27_19-30.log there are no errors here.

Any help would be appreciated.

**Comment by pucherot** [comment]
Please, can you execute this command?
`hostname -I`

**Comment by JosefWaida** [comment]
hostname -I gives me all the IPs...

`192.168.0.109 10.6.0.1 172.18.0.1 172.17.0.1 169.254.136.215 169.254.226.5`

**Comment by pucherot** [comment]
ok, that's the problem: too many IP's

Please check you Local DNS in Pi.hole:
- Pi-hole admin portal -> Local DNS -> DNS Records -> Add new domain /IP
- pi.alert 192.168.1.x
  (replace 192.168.1.x with your Raspberry IP)

alternatively use, this url to access to Pi.Alert admin panel:
- http://192.168.0.109/pialert

**Comment by pucherot** [comment]
Changed `hostname -I` to `ip -o route get 1 | sed -n 's/.*src \([0-9.]\+\).*/\1/p'`
