### ISSUE TITLE
Feature Request: Internet presence monitoring

### ISSUE THREAD

**Issue by MrDKOz** [pucherot/Pi.Alert#63]
Currently it doesn't look like Pi.Alert monitors internet uptime in the Presence section. While I know Pi.Alert couldn't send an email alert if the internet was to drop, but it would be handy to have that information within the Presence section so I can see the points at which my internet connection dropped after the fact.

**Comment by pucherot** [comment]
Is a good point MrDKOz.
I write it down for next versions.

**Comment by pucherot** [comment]
Done.

Available in the next version.
