### ISSUE TITLE
Feature Request - Next button while editing entries

### ISSUE THREAD

**Issue by erikboyer** [pucherot/Pi.Alert#66]
Would be nice that after you finish editing one IP entry, you can click on a "next" button to move on to another entry instead of having to exit out to the main screen and then click on another client entry.

**Comment by pucherot** [comment]
This is a good feature.
I'll evaluate it.

**Comment by pucherot** [comment]
Done

Available in next version.

![image](https://user-images.githubusercontent.com/25605499/115516858-d4890900-a286-11eb-850e-5c90c9767dcd.png)
