### ISSUE TITLE
Missing history drop down menu in devices section ver. 2.70

### ISSUE THREAD

**Issue by MannedMission** [pucherot/Pi.Alert#70]
Since I updated to version 2.70 the history drop down menu (today, last week, last month) is missing on Devices page. However on Events page is still there.

Updated through auto update command line from 2.61.

Thank you for your efforts. This is a great tool! Exceptional implementation. Simple and great.

**Comment by pucherot** [comment]
Yes, is correct.
In the main page (devices list) this option was useful to identify new devices.
Now, new devices are no marked with time (previous dropdown menu).
Now you can mark / unmark "new devices" in each device detail page.

**Comment by MannedMission** [comment]
I see the point now.

Thank you for your quick response.
