### ISSUE TITLE
What is the purpose/meaning of "scan cycle" setting?

### ISSUE THREAD

**Issue by stevehoek** [pucherot/Pi.Alert#72]
I just installed and configured Pi.Alert, naming all of my devices.
I notice some default to 15min scan cycle, others to 1 min (by default, not by my setting it one way or the other)
What is the purpose of the scan cycle settings?  Does it run arp scan less often?
Also, what is the meaning of "scan 1' every 5'" and "scan 12' every 15'" ?  is that hours?  In US the ' character denotes "foot" measurement unit, not time ;)

**Comment by pucherot** [comment]
1 - scans during 1 minute every 5 minutes (12 times an hour)
15 - scans during 12 minutes every 15 minutes (4 times an hour)

For apple devices is better to use long scan cycle (15).
More info:
https://github.com/pucherot/Pi.Alert/blob/main/docs/DEVICE_MANAGEMENT.md#events--alerts-config
