### ISSUE TITLE
Loading spinner won't go away

### ISSUE THREAD

**Issue by jasonwtobe** [pucherot/Pi.Alert#78]
Since upgrading to `Pi.Alert  2.70  (2021-02-01)` I have a loading spinner in the middle of the page which won't go away. 

![image](https://user-images.githubusercontent.com/48776255/106902641-5b532e80-66f9-11eb-9732-901b89233be9.png)

What I've tried:
- running the upgrade script again
- restarting the VM

**Comment by jasonwtobe** [comment]
In the interim, is there a way to "reset" the Pi.Alert installation (eg. start from scratch or uninstall then reinstall)?

**Comment by MrDKOz** [comment]
I had this same issue, however, I left it alone for a bit as I was going to reinstall later, but on visiting the page again it was gone and is working fine. I know it's not a fix or much help at all, but just adding some info to the issue.

**Comment by jasonwtobe** [comment]
After a reinstall I don't get the spinner anymore. Happy to have closed
