### ISSUE TITLE
Python3 in piconfig_install.sh

### ISSUE THREAD

**Issue by BarnardCollier** [pucherot/Pi.Alert#81]
At line 380 of the piconfig_install.sh script, the apt-get is for python instead of python3.  

      sudo apt-get install python -y                              2>&1 >> "$LOG"

This is the same entry as the previous apt-get line for python2.  On my system (Raspbian OS), the above installs python 2 not 3.

I suggest that this is an oversight and that the correct line 380 should be:

      sudo apt-get install python3 -y                              2>&1 >> "$LOG"

**Comment by pucherot** [comment]
Done.
Thank you.
