### ISSUE TITLE
Suggestion: Add indicator to identify clients with Randomized MAC Addresses

### ISSUE THREAD

**Issue by notsponsible** [pucherot/Pi.Alert#87]
WIfi clients running Windows 10, Android 10+, or Apple iOS 14+ all have the capability to randomize their MAC Addresses on a per SSID basis.  For many of these devices, this privacy feature is turned on by default and some of them can shift randomized MAC addresses periodically (for example, Windows 10 and Android 11 can randomize daily).  For diagnostic and troubleshooting purposes, it would be great if Pi Alert can indicate that a device has connected with a randomized MAC address.  If the 7th binary bit in a MAC address is a 1 we know that it is a randomized MAC address.  When converted back to the standard HEX notation, the second character of the OUI will appear as either a 2, 6, A, or an E which indicates a randomized MAC Address.  More information on this can be found [here](https://community.cisco.com/t5/security-documents/random-mac-address-how-to-deal-with-it-using-ise/ta-p/4049321).  By indicating that a device has a randomized MAC address, users can quickly determine whether or not one of their own devices is shifting through random addresses and make the corrections on their own device to allow Pi Alert to remain effective for tracking their network assets and identifying new network devices.

**Comment by jasonwtobe** [comment]
+1 to this request.

**Comment by zigapovhe** [comment]
+1

**Comment by eugef66** [comment]
+1

**Comment by pucherot** [comment]
Great idea

The next version will show if the device uses a random MAC:
![image](https://user-images.githubusercontent.com/25605499/115118642-77e6cf00-9fa4-11eb-8688-3e0635f394cc.png)
![image](https://user-images.githubusercontent.com/25605499/115118665-9cdb4200-9fa4-11eb-8e6b-7cc4053d61b5.png)
