### ISSUE TITLE
Not an issue (so please close!), just a thank you!

### ISSUE THREAD

**Issue by Lissy93** [pucherot/Pi.Alert#88]
Hello @pucherot - 
I hope you don't mind, but I couldn't find another way to leave you a message. I just wanted to say that what you have built is really awesome! Install process was seamless, dashboard is beautiful and it works perfectly and and is incredibly useful. It's clear you've put a lot of time into it, so I just wanted to say a quick thank you. Keep up the amazing work!
P.s if you have a sponsor page, or BTC address, let me know, as I feel like I'd be happy to make a donation.

Cheers,
Alicia

**Comment by pucherot** [comment]
Hello Alicia, sorry for the delay in answering your message.

Thank you very much for the support message, it is very gratifying for me to receive messages like yours.

Thank you very much also for the offer to make a donation. I don't mean to be discourteous, but is not necessary. I built Pi.Alert for my personal use and have decided to package and publish it for the enjoyment of the community.

Cheers,
Puche.
