### ISSUE TITLE
scan other subnets ?

### ISSUE THREAD

**Issue by ErfanDL** [pucherot/Pi.Alert#98]
Hi. I have a mikrotik router on my network and I used 3 different IP range ( 10.5.50.0/24 and 10.5.51.0/24 and 10.5.52.0/24 ) how can I scan all IP range ? the Pi-Alert only see 10.5.51.0/24 network. please help.
thanks.

**Comment by pucherot** [comment]
Next version will allow scan more than one subnet, and will alllow define the interface.

BR
