### ISSUE TITLE
It seems that pi.alert is constantly looking for a domain

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [pucherot/Pi.Alert#99]
resolver1.opendns.com

How can I stop it? Or what could I do to change it? Maybe change it to example.com?

**Comment by pucherot** [comment]
This is used to check your Internet IP changesIt is used to verify changes to your internet IP address.

You can increase the period between checks by modifying the cronjob settings.. By default the period is once every minute:
~~~
*/1 * * * *    python ~/pialert/back/pialert.py internet_IP    >~/pialert/log/pialert.IP.log       2>&1
~~~

**Comment by SodaWithoutSparkles** [comment]
I mean, changing the address to something like example.com, or setting a static IP in `/etc/hosts` for that site?

**Comment by pucherot** [comment]
That wouldn't work

Pi.Alert needs to run the command **`dig + short -4 myip.opendns.com @resolver1.opendns.com`** to know your public ip.
This command use DNS Query to identify your public IP.

**Comment by SodaWithoutSparkles** [comment]
I mean, wouldnt this work too?
`dig +short -4 myip.opendns.com @208.67.222.222`

**Comment by pucherot** [comment]
Yes this would work

In the other hand, you could only set an opendns IP server to resolve "myip.opendns.com"
If opendns changes the IP address of the DNS server, Pi.Alert would stop working.

If you prefer this behaviour, you can change pialert.py to use a static IP.

**Comment by SodaWithoutSparkles** [comment]
They should not do so. A DNS server should have a static IP, and have you ever seen google change their public DNS server IP?

**Comment by fittoiniguez** [comment]
This line: dig + short -4 myip.opendns.com @resolver1.opendns.com always times out for me:
;; connection timed out; no servers could be reached

I run Pihole and unbound, additional have routing in my router to avoid any DNS leak to any upstream server. All is being resolved by unbound.

Since Pi.Alert is working along with Pi Hole, would it be possible to use the DNS from the pihole settings?
http://pi.hole/admin/settings.php?tab=dns

Or add a section to the UI to set the DNS?

**Comment by SodaWithoutSparkles** [comment]
And no, you cannot use DNS other the opendns for querying myip.opendns, since it needs to work with opendns.

You could try setting a static IP for resolver1.opendns.com by using `dig +short -4 myip.opendns.com @208.67.222.222` to see if it would work. 

Also could you provide result of `dig resolver1.opendns.com`?

**Comment by fittoiniguez** [comment]
I changed the line to use the raspberrypi IP, as long as the command does not time out the script continues and "works" I'm able to see my devices in the UI now. 

Thank you for developing this tool, it is very useful!

Here is the output:

pi@raspberrypi:~ $ dig resolver1.opendns.com

; <<>> DiG 9.11.5-P4-5.1+deb10u3-Raspbian <<>> resolver1.opendns.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52982
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;resolver1.opendns.com.         IN      A

;; ANSWER SECTION:
resolver1.opendns.com.  3600    IN      A       208.67.222.222

;; Query time: 38 msec
;; SERVER: 192.168.0.2#53(192.168.0.2)
;; WHEN: Tue Apr 27 10:46:39 CDT 2021
;; MSG SIZE  rcvd: 66

**Comment by SodaWithoutSparkles** [comment]
I think I know why, you blocked all DNS leak, which in this case is what needed.
